### ISSUE TITLE
CHANGELOG.md for ChangeLog in VSCode extension view

### ISSUE THREAD

**Issue by bkonetzny** [felixfbecker/vscode-php-intellisense#101]
Can we get a CHANGELOG.md to see whats new on each release? This is common use for github projects and will be picked up by VSCode too.

**Comment by felixfbecker** [comment]
The problem here is that changes are not done in this repo, but in the language server repo. I am reluctant to duplicate a changelog in both repos.

**Comment by jens1o** [comment]
Maybe use a symlink for this? @felixfbecker

**Comment by felixfbecker** [comment]
you mean a git submodule?! that only works for directories
is the changelog taken from GitHub or from the extension package?

**Comment by jens1o** [comment]
I think from GitHub, because even unupdated extension gets a changelog  that shows what's new.

**Comment by rhyek** [comment]
This is needed. What is new in 1.3.0? I have this extension disabled due to a memory leaks. Does this fix that? I've no idea!

**Comment by felixfbecker** [comment]
@rhyek Do you have an idea how to add one without maintaining it in multiple places? The commit log makes it pretty obvious what changed in 1.3.0: https://github.com/felixfbecker/vscode-php-intellisense/commits/master

**Comment by jens1o** [comment]
Basically, it adds the possibility that the intellisense boots up as soon as there is an .php file in the workspace. This is supported in the next insider and in the next stable release. This really improves the performance, because you can just start when you start editing a file and everything is indexed(or at least the index is a bit bigger).

**Comment by rhyek** [comment]
@felixfbecker the language server and vs code extension repos don't have a synced version number and release schedule from what I can see. Not sure how linking a CHANGELOG.md between the two would help? Nevertheless, what @jens1o says should work, no?

**Comment by jens1o** [comment]
*cough* I created the pr #123 *cough

**Comment by felixfbecker** [comment]
@rhyek The version number is not synced because both follow semver, but I cut a release here whenever a release is done in the LS. Could you elaborate how you think it would work?

**Comment by rhyek** [comment]
@felixfbecker, last release for php-language-server was on April 24th? Not sure I understand.

**Comment by jens1o** [comment]
But this extension can offer updates as well, for example anything which is isn't handled by the lsp, for example memory restrictions for the server, or a note for `vscode` when it should launch this extension.

**Comment by rhyek** [comment]
Maybe just keeping a CHANGELOG.md for each project in their respective repo's, linking to the language server's in this one's, and keeping a synced release schedule should do the trick?

In this changelog you could, for example, provide a link in the 1.3.0 entry to a specific release tag or line number on the language server's CHANGELOG.md?

Or just a general link to language server's change log at the top of this one.

You could also consider concatenating the language server's changelog into this repo's.

**Comment by jens1o** [comment]
Awesome!
