### ISSUE TITLE
Unknown configuration setting

### ISSUE THREAD

**Issue by kastaldi** [felixfbecker/vscode-php-intellisense#103]
I use VS Code 1.11.1 and PHP Intellisense 1.1.5. The extension complains about not being able to find PHP 7 so I try to set "php.executablePath" in settings.json and VS code underlines this setting with the message "unknown configuration setting". I edit the php files on a remote webserver so I just need PHP to check syntax and format PHP  files, I'll add c:\php to Windows PATH to fix this error but I just wanted to report this problem.

**Comment by felixfbecker** [comment]
I think it's missing from package.json. PR appreciated.

**Comment by erwinw** [comment]
Looking forward to a new version - would love getting rid of the warning! 👍

**Comment by felixfbecker** [comment]
fixed

**Comment by JustinReinhart** [comment]
This appears to have been changed to "php.validate.executablePath" .  I am leaving a note here because I came here via google thinking it was a bug and it took me a long time to find the solution. Had it been on this page it would have saved me lots of time. Hoping it saves others.
