### ISSUE TITLE
[FEATURE] Should be command to rerun the server

### ISSUE THREAD

**Issue by GeraldNDA** [felixfbecker/vscode-php-intellisense#104]
Usually when I open vscode it parses a whole bunch of files, but doesn't seem to parse (or at least post it into the output log) afterwards. Which doesn't seem to effect my regular parsing stufts but if I update my underlying codebase I don't want to reload the whole window. 

I think a command for this functionality would be in order ...

**Comment by felixfbecker** [comment]
This would be better solved through `didChangeWatchedFiles`
