### ISSUE TITLE
CTRL+Click: Navigate over functions from required_once files

### ISSUE THREAD

**Issue by diogoca** [felixfbecker/vscode-php-intellisense#107]
Suppose that I have foo() function on file.php

```
require_once('file.php')
foo();
```

I cant navigate to foo function when I try to ctrl+click hover that.
Does anybody know if is possible?

**Comment by felixfbecker** [comment]
if `foo()` is defined in the same namespace there should be no problem. Closing as not related to the extension itself.

**Comment by diogoca** [comment]
@felixfbecker no namespace was set, old strucutred code... :( only a simple `function foo()` we have on that file.php
