### ISSUE TITLE
Find all symbols always display no list

### ISSUE THREAD

**Issue by to2false** [felixfbecker/vscode-php-intellisense#109]
I don't know how the function find all symbols works.

It only can display list in file with several functions, it can't show once the functions get more. For example, I use it when I look in laravel source code.

**Comment by felixfbecker** [comment]
Cannot reproduce. Please give the exact steps you do.

**Comment by to2false** [comment]
![image](https://cloud.githubusercontent.com/assets/21302817/25209106/62465c6e-25ab-11e7-8556-c32f9fbe3559.png)
I just `command+shift+o`, it always keep the state.

**Comment by jens1o** [comment]
@to2false Could we get the file?

**Comment by felixfbecker** [comment]
Note there is a difference between workspace symbol search and document symbol search

**Comment by jens1o** [comment]
In any case, there should be something unless the file is not empty.

**Comment by felixfbecker** [comment]
Log output in the output panel, dev tools?

**Comment by to2false** [comment]
```
[Extension Host] ernel"},{"name":"prependMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":189,"character":4},"end":{"line":196,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"pushMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":204,"character":4},"end":{"line":211,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"bootstrap","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":218,"character":4},"end":{"line":223,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"dispatchToRouter","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":230,"character":4},"end":{"line":237,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"hasMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":245,"character":4},"end":{"line":248,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"bootstrappers","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":255,"character":4},"end":{"line":258,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"reportException","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":266,"character":4},"end":{"line":269,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"renderException","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":278,"character":4},"end":{"line":281,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"getApplication","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":288,"character":4},"end":{"line":291,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"}],"id":65,"jsonrpc":"2.0"}Content-Type: application/vscode-jsonrpc; charset=utf8
Content-Length: 6857

{"result":[{"name":"Illuminate\\Foundation\\Http","kind":3,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":2,"character":10},"end":{"line":2,"character":36}}},"containerName":"Illuminate\\Foundation"},{"name":"Kernel","kind":5,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":13,"character":0},"end":{"line":292,"character":1}}},"containerName":"Illuminate\\Foundation\\Http"},{"name":"app","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":20,"character":14},"end":{"line":20,"character":18}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"router","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":27,"character":14},"end":{"line":27,"character":21}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"bootstrappers","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":34,"character":14},"end":{"line":42,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"middleware","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":49,"character":14},"end":{"line":49,"character":30}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"routeMiddleware","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":56,"character":14},"end":{"line":56,"character":35}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"__construct","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":65,"character":4},"end":{"line":73,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"handle","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":81,"character":4},"end":{"line":102,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"sendRequestThroughRouter","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":110,"character":4},"end":{"line":122,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"terminate","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":131,"character":4},"end":{"line":149,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"gatherRouteMiddlewares","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":157,"character":4},"end":{"line":164,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"parseMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":172,"character":4},"end":{"line":181,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"prependMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":189,"character":4},"end":{"line":196,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"pushMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":204,"character":4},"end":{"line":211,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"bootstrap","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":218,"character":4},"end":{"line":223,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"dispatchToRouter","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":230,"character":4},"end":{"line":237,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"}
```

**Comment by to2false** [comment]
[Extension Host] ernel"},{"name":"prependMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":189,"character":4},"end":{"line":196,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"pushMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":204,"character":4},"end":{"line":211,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"bootstrap","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":218,"character":4},"end":{"line":223,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"dispatchToRouter","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":230,"character":4},"end":{"line":237,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"hasMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":245,"character":4},"end":{"line":248,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"bootstrappers","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":255,"character":4},"end":{"line":258,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"reportException","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":266,"character":4},"end":{"line":269,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"renderException","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":278,"character":4},"end":{"line":281,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"getApplication","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":288,"character":4},"end":{"line":291,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"}],"id":65,"jsonrpc":"2.0"}Content-Type: application/vscode-jsonrpc; charset=utf8
Content-Length: 6857

{"result":[{"name":"Illuminate\\Foundation\\Http","kind":3,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":2,"character":10},"end":{"line":2,"character":36}}},"containerName":"Illuminate\\Foundation"},{"name":"Kernel","kind":5,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":13,"character":0},"end":{"line":292,"character":1}}},"containerName":"Illuminate\\Foundation\\Http"},{"name":"app","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":20,"character":14},"end":{"line":20,"character":18}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"router","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":27,"character":14},"end":{"line":27,"character":21}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"bootstrappers","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":34,"character":14},"end":{"line":42,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"middleware","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":49,"character":14},"end":{"line":49,"character":30}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"routeMiddleware","kind":7,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":56,"character":14},"end":{"line":56,"character":35}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"__construct","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":65,"character":4},"end":{"line":73,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"handle","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":81,"character":4},"end":{"line":102,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"sendRequestThroughRouter","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":110,"character":4},"end":{"line":122,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"terminate","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":131,"character":4},"end":{"line":149,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"gatherRouteMiddlewares","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":157,"character":4},"end":{"line":164,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"parseMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":172,"character":4},"end":{"line":181,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"prependMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":189,"character":4},"end":{"line":196,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"pushMiddleware","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":204,"character":4},"end":{"line":211,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"bootstrap","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":218,"character":4},"end":{"line":223,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"},{"name":"dispatchToRouter","kind":6,"location":{"uri":"file:\/\/\/Users\/juwai\/Projects\/juwai-com-v2\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","range":{"start":{"line":230,"character":4},"end":{"line":237,"character":5}}},"containerName":"Illuminate\\Foundation\\Http\\Kernel"}

**Comment by to2false** [comment]
It's easy to stop at a point.

**Comment by pioneerskies** [comment]
I notice same behaviour as OP but on workspace symbols search. File symbol search always works as expected here.

**Comment by felixfbecker** [comment]
Closing as inactive, wrong repo and not enough info
