### ISSUE TITLE
Honor php.executablePath

### ISSUE THREAD

**Issue by zero2999** [felixfbecker/vscode-php-intellisense#11]
Hi. your work is very good. but you know not all use php in our projects. Some use php 5 or less. You know you should allow choose the version of php or that automatically detects and should also allow use more than one version of php

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/felixfbecker/php-language-server/issues/23

I'm planning to read the `php.executablePath` setting to support multiple versions, but generally, you _can_ use multiple versions (I do that myself), just PHP7 needs to be in PATH atm.

PRs welcome!

**Comment by wangroute** [comment]
where is php.executablePath?

**Comment by felixfbecker** [comment]
In settings.json. But it is not implemented yet

**Comment by grafikerinbiri** [comment]
How about Xampp? I tried like this: "php.validate.executablePath": "D:\Archive\Server\php"
