### ISSUE TITLE
Resolve/expand namespaces?

### ISSUE THREAD

**Issue by nerdo** [felixfbecker/vscode-php-intellisense#110]
I'm not sure if this is the right place to ask, but is there a way to resolve php namespaces with this plugin?

Essentially I'm looking to be able to do something very similar to this Sublime plugin https://github.com/erichard/SublimePHPCompanion.

**Comment by felixfbecker** [comment]
No, this is not the right place to ask

> Note: This is just the VS Code extension that spawns the actual language server. The language server itself is implemented purely in PHP in its own repository, all features need to be implemented there and all issues should be reported there.

Also don't really understand the feature
