### ISSUE TITLE
Crashing after update

### ISSUE THREAD

**Issue by beeblebrox3** [felixfbecker/vscode-php-intellisense#112]
After the last update, the language server is crashing after a few seconds.
This happen to me on two different machines, one with linux mint 18 and the other with elementary loki. Are different projects and different versions of php.

![vscode - php](https://cloud.githubusercontent.com/assets/767624/25317653/2f9da5ce-2853-11e7-93de-6d2127f3cfd4.png)

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/pull/363
