### ISSUE TITLE
Return type PHP 7.1

### ISSUE THREAD

**Issue by Gauss23** [felixfbecker/vscode-php-intellisense#116]
Hello,

the languageserver is crashing when defining a function with a return type of "?string" instead of "string". "?string" means it´s a string or null. Same for "?int" etc.

It crashes with: 
```
[Error - 17:54:56] Request textDocument/hover failed.
  Message: ErrorException: Object of class PhpParser\Node\NullableType could not be converted to string in XXXXXXX\.vscode\extensions\felixfbecker.php-intellisense-1.2.1\vendor\felixfbecker\language-server\src\DefinitionResolver.php:792
Stack trace:
```

Best regards and thank you for the excellent work!

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/pull/292
https://github.com/felixfbecker/php-language-server/issues/290
