### ISSUE TITLE
Setting protected properties in __construct

### ISSUE THREAD

**Issue by rogierverbrugge** [felixfbecker/vscode-php-intellisense#118]
When I use __construct() to setup dependency injection the protected property that I set won't be available through $this.

It works when I use it directly
![With helper](http://imgur.com/MONrGYh.png)

But not when it's a property
![No helper](http://i.imgur.com/ND03kqe.png)

Any idea how that's possible?

**Comment by jens1o** [comment]
What's your doc comment for the property? It relies on it

**Comment by rogierverbrugge** [comment]
Thank you! Had to change it to AuthService instead of App\Services\AuthService.

**Comment by felixfbecker** [comment]
Fully qualified names must start with a leading backslash, otherwise they are resolved relative to the current namespace.
