### ISSUE TITLE
Bug after move folder project, and how i can clean/refresh cache system of php-intellisense ?

### ISSUE THREAD

**Issue by v20100v** [felixfbecker/vscode-php-intellisense#119]
If i move folder of my project, php-intellisense doesn't work when i want go to definition of a class (in vendor folder). I think, it doesn't find reference in this cache system. 

In output PHP Language Server, I see this :
```
Parsing file:///d:/Working/PSTI/src/web/app_dev.php
Parsing file:///d:/Working/PSTI/src/web/config.php
[Info  - 11:24:05] 40 Packages
[Info  - 11:24:05] Restored composer/ca-bundle:1.0.7 from cache
[Info  - 11:24:05] Restored doctrine/annotations:1.2.7 from cache
[Info  - 11:24:05] Restored doctrine/cache:1.6.1 from cache
(...)
[Info  - 11:24:15] Restored zendframework/zend-validator:2.4.11 from cache
[Info  - 11:24:15] All 6053 PHP files parsed in 26 seconds. 370 MiB allocated.
```

How can i refresh this cache system of vscode-php-intellisense ?

**Comment by felixfbecker** [comment]
just delete the cache folder, e.g. in Powershell
```powershell
rm -re -fo "$env:LocalAppData\PHP Language Server"
```

**Comment by felixfbecker** [comment]
Did you try the PS command I gave you?

**Comment by v20100v** [comment]
Ok just tired and i found in ... %USERPROFILE%\AppData\Local\PHP Language Server

**Comment by felixfbecker** [comment]
I don't know why you use %USERPROFILE%, you could have just used the command I gave you which uses %LocalAppData%, but whatever works for you

**Comment by asule90** [comment]
@felixfbecker sorry to re-open this issue, i dont know how to do this in linux ubuntu?
intellisense in my php project keep looking in the old directory. i've tried re-install this extension and clear all ~/.config/Code cache directory, but still no luck.

**Comment by felixfbecker** [comment]
Check ~/.phpls or XDG_CACHE_DIR
