### ISSUE TITLE
PHP7.1.0-RC1 not supported

### ISSUE THREAD

**Issue by CyrilCharlier** [felixfbecker/vscode-php-intellisense#12]
VSCode Version: 1.6.0-insider
OS Version: Win10
Steps to Reproduce:
Install PHP 7.1.0-RC1 and you will get this error :

The language server needs at least PHP 7 installed and in your PATH. Version found: 7.1.0-RC1
![2016-09-19_10h02_57](https://cloud.githubusercontent.com/assets/11455745/18627611/2acf6092-7e5c-11e6-8ebe-68a318f62087.png)

**Comment by felixfbecker** [comment]
What is the output of `php -v`?

**Comment by CyrilCharlier** [comment]
This is output : 

>php -v
PHP 7.1.0RC1 (cli) (built: Aug 31 2016 22:00:02) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

**Comment by felixfbecker** [comment]
3a9f50312b878ee40591b32ee37f7015edbc2130
