### ISSUE TITLE
Project reindexed at startup, autocomplete unavailable until finished

### ISSUE THREAD

**Issue by insprintorob** [felixfbecker/vscode-php-intellisense#122]
I have a very large WordPress project with 10000+ PHP files. All up they amount to 250MB. Running Mac OS X El Capitan / Vscode 1.12.2 / PHP 7.1.4 
```
[Info  - 2:30:25 PM] All 10195 PHP files parsed in 640 seconds. 250 MiB allocated.
```
When I start vscode, the language server fires up in the background as starts indexing as usual. This takes about 10-15 minutes to complete while the server takes up around 90% of cpu.  During this time, intellisense features are unavailable like code completion, go to definition etc.

Closing and restarting vscode causes the whole project to be re-indexed again.

I have another much smaller project for which this isn't so much a problem as the indexation is fast because of the small number of files.

Is there a way to cache the results of the previous index so that the whole project doesn't have to be scanned on each startup? Maybe just changed files?

**Comment by felixfbecker** [comment]
Closing as unrelated to the extension. If you have a suggestion how to improve caching please open an issue at the [language server repository](https://github.com/felixfbecker/php-language-server).
