### ISSUE TITLE
Hell broke loose after update to 1.4.1

### ISSUE THREAD

**Issue by ADmad** [felixfbecker/vscode-php-intellisense#127]
Sorry for the hyperbole in the title but since the release of 1.4 series of the extension which uses v4.5 of the language server, the language server constantly keeps crashing. IMHO it was premature to do stable release of this extension which uses the new language parser. I will submit issues on the language server repo soon to help fix the issues but I suggest making stable versions of this extension use the old language parser until the new one has gone through some more real world testing. Separate beta series could be started for trying out the new parser.

**Comment by ADmad** [comment]
VSCode 1.13 auto updates extensions which makes matters worse.

**Comment by jens1o** [comment]
You can disable auto update at the upper right-hand corner in the extensions viewlet.

**Comment by ADmad** [comment]
> You can disable auto update at the upper right-hand corner in the extensions viewlet.

Yes I can, but that's not the point. "Stable" releases of this extension should not be using the new parser until it has some more testing.

**Comment by jens1o** [comment]
I tested it for over 2 weeks and I didn't found any bugs once the switch was done, I'm curious I forgot so many... Could you report them as soon as possible, please?

**Comment by ADmad** [comment]
I am sure you did you best but just one or two individuals testing such a complex tool is not sufficient :) I will try to submit issues ASAP.

Btw how can I revert to an older version of the extension?

**Comment by jens1o** [comment]
1.3.0 using old parser:
https://felixfbecker.gallery.vsassets.io/_apis/public/gallery/publisher/felixfbecker/extension/php-intellisense/1.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Comment by felixfbecker** [comment]
@ADmad There is a vsix for 1.3.0 on the releases page: https://github.com/felixfbecker/vscode-php-intellisense/releases/tag/v1.3.0
Sorry for the inconvenience, please open all the issues you see at the language server repo

**Comment by felixfbecker** [comment]
Sorry, I made a mistake when building the vsix (only added automatic vsix release very recently). Should be fixed now.

**Comment by ADmad** [comment]
No worries, thanks.

**Comment by ADmad** [comment]
https://github.com/felixfbecker/php-language-server/issues/418#issuecomment-309291446

**Comment by jens1o** [comment]
Happy to hear that! :)
