### ISSUE TITLE
Symbol search hangs VSCode

### ISSUE THREAD

**Issue by slashrsm** [felixfbecker/vscode-php-intellisense#130]
Hi, 

first I'd like to thank you for your work with this extension and the language server!

I have quite a big project (Drupal 8, a bunch of modules, lots of dependencies in vendor/). Upon opening the VSC PHP language server fires and starts indexing. I can see the process consuming CPU power and output being displayed. All good so far:

```
[Info  - 18:00:31] All 16991 PHP files parsed in 450 seconds. 520 MiB allocated.
```

OK, my codebase is now indexed. Auto complete seems to be working, jump to definition as well, ... Sometimes they are a bit laggy but nothing too serious. Then I try to use the symbol search panel. At this point VSC goes nuts; CPU usage goes through the roof (VSC process, not language server), interface becomes totally unresponsive and it stays like that for minutes. 

It is not happening if I disable PHP Intellisense. Any clues?

Thanks, 

JAnez

**Comment by MadHed** [comment]
My guess is that's because vscode is rendering the result list synchronously in the main thread. I had the same thing happen with "only" 5000 files.
A Solution would be to throttle the rendering but that needs to be implemented on VSCode's side.

**Comment by jens1o** [comment]
I also think you rather create a issue at `vscode` and reference it here.

**Comment by slashrsm** [comment]
Done. Thanks!
