### ISSUE TITLE
.editorconfig should be priority on Format Document

### ISSUE THREAD

**Issue by leocaseiro** [felixfbecker/vscode-php-intellisense#131]
@felixfbecker, I believe this is an issue with VSCode instead of the Language Service. Please forgive me if not.

Every time I call Format Document, the **php-intellisense** is overriding my `.editorconfig` settings.

For example, if I set the `indent_style = tab`. It works on press key `tab`. The editor shows me tabs instead of spaces. However, if I call `cmd+shift+p` and type the command: `Format Document`, it changes back to space.

Do you know what's wrong? Thanks

**Comment by felixfbecker** [comment]
Formatting is handled by PHP CodeSniffer, which can be configured with an XML file. Please refer to the CodeSniffer docs
