### ISSUE TITLE
Check directory permissions

### ISSUE THREAD

**Issue by bweston92** [felixfbecker/vscode-php-intellisense#132]
Don't fail when scanning directories that the process doesn't have permission to, just skip them.

For example this makes Intellisense not work at all.
```
UnexpectedValueException: RecursiveDirectoryIterator::construct(/home/bweston/workspace/src/legalweb.tech/cosmicapp/cosmicapp.co.uk/.persistent/mysql/sys): failed to open dir: Permission denied in /home/bweston/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/webmozart/glob/src/Iterator/RecursiveDirectoryIterator.php:43
```

**Comment by nyon** [comment]
I have the same problem. A good solution would be to exclude all directories that are also excluded by visual studio code (files.exclude).

**Comment by aciobanu** [comment]
+1

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/felixfbecker/php-language-server/issues/462
