### ISSUE TITLE
php symbol icon

### ISSUE THREAD

**Issue by MacFlurry** [felixfbecker/vscode-php-intellisense#134]
Hello,

> Ask for a feature.

Is it possible to add symbol icons like in php storm?
here an example 
![capture d ecran 2017-07-15 a 02 20 57](https://user-images.githubusercontent.com/8139322/28234864-e0dd7458-6904-11e7-875b-70dac4d85f80.png)

Thanks for your great work.

MacFlurry

**Comment by felixfbecker** [comment]
You can see the icons VS Code uses here: https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions

**Comment by MacFlurry** [comment]
Hello, I mean, symbols like class overrode in another class, in phpStorm , they appear like this
![capture d ecran 2017-07-15 a 10 17 41](https://user-images.githubusercontent.com/8139322/28237757-fea37cde-6946-11e7-90c1-4fc0c920093b.png)

![capture d ecran 2017-07-15 a 10 17 59](https://user-images.githubusercontent.com/8139322/28237759-017797f6-6947-11e7-8a02-570e5fae8517.png)

**Comment by felixfbecker** [comment]
I would recommend you to suggest that at the vscode repo first, this is not possible to control through LSP

**Comment by MacFlurry** [comment]
oh ok,

thanks for your answer.

Best regards,
