### ISSUE TITLE
Update Libraries for PHP 7.2+ support

### ISSUE THREAD

**Issue by KalleZ** [felixfbecker/vscode-php-intellisense#139]
Hi

I'm a first time user, and I downloaded the addon directly from VSCode recently, however it seems it includes an old version of the 'PHP Tolorent Parser' from Microsoft.

Whenever you select some code, the output will annoy you as there is an error, which was fixed in:
https://github.com/Microsoft/tolerant-php-parser/commit/bb15f0051a924b8d412710eda9977d063998da99

However this addon seems not to have been updated to include this fix

**Comment by shrop** [comment]
I ran into this kind of issue and downgraded to PHP 7.1. Would be great to support 7.2+.
