### ISSUE TITLE
Folder exclude option

### ISSUE THREAD

**Issue by Sethios** [felixfbecker/vscode-php-intellisense#141]
So far I'm happy how the extension works and the syntax error is great BUT a folder exclusion option would be great since I use a "file backup" extension that saves a backup of a file every now and then in a folder within the project. 
That said, once I start up VSC I always get 99+ syntax errors in the problems tab, all pointing to my backup folder (that obviously has unfinished code since it saves in the middle of my typing). 
Only workaround is to set the backups be saved outside the project but that still leaves an issue of "digging"  in unwanted folders.

If I missed this setting somewhere, sorry :)

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/issues/164
https://github.com/felixfbecker/php-language-server/issues/159
