### ISSUE TITLE
VSCode extension forces focus to output panel during parsing

### ISSUE THREAD

**Issue by mitchellnemitz** [felixfbecker/vscode-php-intellisense#144]
This is a VSCode Extension specific issue, and has nothing to do with the language server.

**Description**

I have a decently large project that takes about ~2 minutes for the language server to parse, and during that time the VSCode extension refuses to give up focus of the "output" panel. I would like to be able to use the integrated terminal during the first couple minutes of opening VSCode, but it seems that on every response from the language server the extension forces the focus back to the output panel instead of simply logging in the background.

Ideally the output from the language server would write in the background and possibly update a message in the status bar with the parsing progress instead of repeatedly taking focus.

The [Crane project output utility](https://github.com/HvyIndustries/crane/blob/master/client/src/utils/Debug.ts) seems to achieve this behaviour like so:

```
var outputConsole = window.createOutputChannel("PHP Language Server");
outputConsole.appendLine(`${message}`);
```

But from what I can tell, this extension simply `console.log(...)`'s everything, which is likely the source of the "bug" (admittedly just a frustrating inconvenience) I'm experiencing.

**Comment by felixfbecker** [comment]
I cannot reproduce this. The output panel doesn't get focused for me during parsing.

**Comment by anshulsahni** [comment]
This happens very regularly now and had to disable the extension to stop this annoying focussing of output panel while working.

**Comment by maxwellhibbert** [comment]
Happening to me too. Quite frustrating.

**Comment by lvl99** [comment]
This is a real pain and constantly happens, driving me to the point of removing the extension!
