### ISSUE TITLE
Extension redundant?

### ISSUE THREAD

**Issue by cvharris** [felixfbecker/vscode-php-intellisense#146]
What is this extension even for? It's not explicit in the README even though it is one of the most popular VSCode libraries.

This extension feels redundant because I can have it off and still get PHP Intellisense. Plus with this extension enabled I've experienced nothing but performance costs. Even though I've installed the extension and disabled `php.suggest.basic` any PHP intellisense is significantly slower. A `php` process runs in the background and devours my CPU. There is a delay of about 800ms that is annoyingly impactful. Without this extension turned on PHP intellisense works perfectly on its own.

If there are added bonuses for using this extension over the basic language server that ships with VSCode, could you outline them in the README?

Thanks!

**Comment by felixfbecker** [comment]
The README has large gifs showing every single major feature of this extension. Did you even try a single one of the usages shown with just the basic IntelliSense on?

**Comment by cvharris** [comment]
I have tried all of the examples, what I'm saying is they're the exact same as the php-language-server

**Comment by felixfbecker** [comment]
This extension _is_ the PHP language server, packaged for VS Code

**Comment by cvharris** [comment]
So, like I said in the issue, why do I get great PHP Intellisense without this extension turned on, and why is it performance impacting when it is on?

**Comment by felixfbecker** [comment]
I don't know what you are talking about - none of the examples shown in the gifs work with just the basic IntelliSense (this extension disabled and assuming you have no other extension installed)

**Comment by cvharris** [comment]
For the features that overlap between PHP Intellisense and the language-server, does this _add_ anything special or is it merely re-implementing whatever's in the server? I get great code completion, hover, and method function definition/intellisense from the language-server alone. However those are listed as features in this extension as well and I want to know what's different about them that might warrant using the extension. The only things missing from the language-server (so far as I can tell) are Symbols info and Go To Definition which I personally don't need. This felt like a good issue to open especially since this extension slows things down for me significantly and spins up a CPU-churning `php` process. Does that make sense?

**Comment by felixfbecker** [comment]
How do you install the language server in VS Code without this extension?
This extension is not reimplementing anything, it just wraps the language server so it can be installed in VS Code. You can't install the language server directly

**Comment by cvharris** [comment]
how can I tell if the language server is somehow running on its own without the extension

**Comment by cvharris** [comment]
so now it is clear to me what the difference here is. The extension enables the language server, but there are some PHP features built-in to VSCode that is not the language-server. Is that correct?

**Comment by roblourens** [comment]
VS Code has some very basic PHP support builtin, but it's typically pretty useless. The intellisense you get is just words on the page and PHP keywords, it doesn't know the types of variables and it can't intelligently give suggestions. And like Felix said, it doesn't support the features listed in the readme of this extension, at least not well.

**Comment by cvharris** [comment]
It sounds stupid to say but that only seems obvious now. Didn't realize the php-language-server wasn't the same as the built-in stuff. Now I see the differences in how well code completion works, but the performance issues I'm experiencing when I first open a project made me wonder how this was worth using. I'll document the issue on the php-language-server repo.

**Comment by naknak987** [comment]
@cvharris 
Are you using the 32 or 64 bit version of VSCode?
@felixfbecker 
I've been using this extension for months and haven't had any performance issues. Then a few days ago I finally updated to the 64 bit version of VSCode and have had nothing but performance issues in regards to your extension.
Can any other users confirm issues after changing from 32 to 64 bit VSCode?
