### ISSUE TITLE
how do i have it store intellisense data, so it doesnt get rerun on every program start

### ISSUE THREAD

**Issue by OliverLeitner** [felixfbecker/vscode-php-intellisense#147]
as the title says...

i would like to reduce the system i/o load by have it not rescan stuff it already scanned.

is that possible?

**Comment by felixfbecker** [comment]
It already saves (caches) the index, but will still reindex because the files could have changed since the last run. I would be open to a PR that implements an option for this

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#466
