### ISSUE TITLE
It can't find the define!

### ISSUE THREAD

**Issue by ancon** [felixfbecker/vscode-php-intellisense#149]
when I rename the folder , it can't find the define!
![default](https://user-images.githubusercontent.com/6762451/29960694-483e22f0-8f2f-11e7-81bd-36c9f8e391aa.png)

**Comment by felixfbecker** [comment]
Please delete `%USERPROFILE%\AppData\Local\PHP Language Server\Cache` and restart your editor

**Comment by ancon** [comment]
@felixfbecker many thanks, it work!
