### ISSUE TITLE
PHP executable via docker. Is this possible?

### ISSUE THREAD

**Issue by csmcgee** [felixfbecker/vscode-php-intellisense#150]
My apologies if this should be in the language-server repo.

I would like to know if php executable path via docker container is supported with this integration. I know the vscode-php-debug extension supports remote server (which works well with my docker container).

If this isn't supported, would this be in the roadmap or does this present too much effort?

Thanks for your help.

**Comment by felixfbecker** [comment]
Could you explain the use case?

**Comment by kralos** [comment]
@csmcgee Create a `/bin/sh` wrapper to your docker container and then point PHP Intellisense at the wrapper:

```sh
#!/bin/sh

docker run \
    --network=host \
    --rm \
    -e HOME="$HOME" \
    -u $(id -u):$(id -g) \
    -v "$HOME":"$HOME" \
    -w "$PWD" \
    php:7-alpine \
    php "$@"

exit $?
```
Please note you will need to map in any volumes you require, i've assumed your `$HOME` dir here.


```json
{
  "php.executablePath": "/somewhere/php7wrapper",
  "php.suggest.basic": false
}
```

@felixfbecker Maybe you should shove this somewhere in your documentation?

**Comment by skyred** [comment]
I just published this Docker image to support this use case https://github.com/INsReady/docker-vscode-php/

**Comment by philippefuentes** [comment]
Hello there, 
How could I define a relative path for php.executablePath ?
ex:
 "php.executablePath": "../myphp.exe",

thanks

**Comment by felixfbecker** [comment]
@philippefuentes that has nothing to do with this issue. Please ask on Gitter or StackOverflow.

**Comment by philippefuentes** [comment]
ok, sorry about that @felixfbecker

**Comment by lalop** [comment]
@kralos juste tried your solution but I get this error in vs code 

`Error spawning PHP: Command failed: /somewhere/php7wrapper --version`

And if I run it in the terminal I get 

`return: can only 'return' from a function or sourced script`

**Comment by kralos** [comment]
@lolop
`/somewhere/php7wrapper` should be the shell file you made

e.g. if you created a file in `/somewhere/php7wrapper` with the following contents
and `chmod 755 /somewhere/php7wrapper`

```sh
#!/bin/sh

docker run \
    --rm \
    -i \
    --network=host \
    -v "$HOME":"$HOME":ro \
    -u $(id -u) \
    -w "$PWD" \
    php:7-alpine \
    php "$@"

return $?
```

But put it wherever you want. A nice place might be `~/bin/php-vscode`

**Comment by lalop** [comment]
:)
I kept the path from your comment to continue the discussion but actually on my comptuer I put this code in `~/bin/php-7`
For information I use osx maybe this is related.

**Comment by kralos** [comment]
@lalop Sorry, my bad. Try this at the end:

```sh
exit $?
```

This might not be super important, it's just returning the exit code from the docker run so the caller knows if the command worked or not. I don't have an osx host to test on but I think return might not work on it.

**Comment by lalop** [comment]
That solves the error prompt thank you but I can't see any improvement in autocompletion, is that normal ?

**Comment by Angelinsky7** [comment]
I manage to make this work, but i need some minor change in your extension (yes i know it's starting bad)

here's my custom php "executable"

```
@echo off
SETLOCAL ENABLEDELAYEDEXPANSION
SET MATCH=C:\Users\Steven\.vscode\extensions\felixfbecker.php-intellisense-2.2.2
SET REPLACE=/vscode
SET INPUT_ARG=%*
SET "PHP_ARG=!INPUT_ARG:%MATCH%=%REPLACE%!"
SET "PHP_ARG=%PHP_ARG:\=/%"

docker run -i --rm -v "%CD%":/var/ctx -v "%MATCH%":%REPLACE% -w /var/ctx php:7-cli php %PHP_ARG%
```

setting the vscode properties :
`"php.executablePath": "D:\\Projects\\libraries\\bin\\\\_php_vscode_7.bat"`

and the modification @line 66 in extension.js : 
```
const serverOptions = () => new Promise((resolve, reject) => {
            // Use a TCP socket because of problems with blocking STDIO
            const server = net.createServer(socket => {
                // 'connection' listener
                console.log('PHP process connected');
                socket.on('end', () => {
                    console.log('PHP process disconnected');
                });
                server.close();
                resolve({ reader: socket, writer: socket });
            });
            // Listen on random port
            server.listen(0, '0.0.0.0', () => {
                // The server is implemented in PHP
                const childProcess = child_process_1.spawn(executablePath, [
                    context.asAbsolutePath(path.join('vendor', 'felixfbecker', 'language-server', 'bin', 'php-language-server.php')),
                    '--tcp=192.168.1.127:' + server.address().port,
                    '--memory-limit=' + memoryLimit
                ]);
                childProcess.stderr.on('data', (chunk) => {
                    vscode.window.showErrorMessage(chunk + '');
                    console.error(chunk + '');
                });
                childProcess.stdout.on('data', (chunk) => {
                    vscode.window.showErrorMessage(chunk + '');
                    console.log(chunk + '');
                });
                return childProcess;
            });
        });
```

So now, the why...
1) You send the path of the exe as a window absolute path :
`C:\Users\Steven\.vscode\extensions\felixfbecker.php-intellisense-2.2.2\vendor\felixfbecker\language-server\bin\php-language-server.php`
but for this to work in docker in need a linux path :
`/vscode/vendor/felixfbecker/language-server/bin/php-language-server.php`
i could change this line `context.asAbsolutePath(path.join('vendor', 'felixfbecker', 'language-server', 'bin', 'php-language-server.php')),` but i was not sure how to do it

2) The server listen to 127.0.0.1 but it need to be 0.0.0.0
3) The client access to 127.0.0.1 but it need to be the current ip address of the host (i dont know how to do it correctly so i hardcoded the value : 192.168.1.127

So now my "demands"

Is it possible to have a least two new settings :
1) The server listening address 
2) The server target address

or even a new boolean setting telling the default options (but harder) : 
false : (listening+target = 127.0.0.1) 
true : listening = 0.0.0.0 and target = current host ip address

we could even have another setting to tell if the path should be relative or absolute (and relative to what...) so we could just have a simple script running the docker php image

Thanks for you amazing extension, i would do a pr myself but sadly i absolutely don't know how to do it correctly... and certainly some people use your extension and php in docker another way that mine, so it could be place to talk.

**Comment by pavels-hyuna** [comment]
Related
#11328

**Comment by FabianKoestring** [comment]
What about creating a pr. We have the same problem. We want to use vscode but we cant manage how to define remote (docker) php executable.

**Comment by thejacer87** [comment]
any update on this? using docker (lando) for my php project and need to set the path somehow. this was fairly easy to setup in phpstorm, but i wanna get away from the intellij eco system

**Comment by martin-sweeny** [comment]
Yeah, why is this closed? The solution propsed by @skyred isn't what we're looking for. 

We want local VS Code to be able to use php binary from within a Docker container (like [Lando](https://lando.dev) or [Devilbox](https://devilbox.org)), not run VS Code within a Docker container alongside php

**Comment by martin-sweeny** [comment]
For example, [this Devilbox thread](https://devilbox.discourse.group/t/how-to-access-php-binary-from-host/191) says you can use `docker-compose exec php php SOME_COMMAND` but when 
adding the following to workspace settings:
```
    "php.executablePath": "docker-compose exec php php"
```

it still cannot read the executable

**Comment by LucasMaliszewski** [comment]
I know this is close, but if you are like me trying to find a solution, you can name the container and use `docker exec NAME (NOT CONTAINER ID) php`

According to the docks you just have to put this in your 


> For example, [this Devilbox thread](https://devilbox.discourse.group/t/how-to-access-php-binary-from-host/191) says you can use `docker-compose exec php php SOME_COMMAND` but when adding the following to workspace settings:
> 
> ```
>     "php.executablePath": "docker-compose exec php php"
> ```
> 
> it still cannot read the executable

Not sure if you found a solution or not. Let me know if not I have one for you.

**Comment by masiorama** [comment]
I'm interested too in what @martin-sweeny is asking.

**Comment by Stromus** [comment]
I think i found a way to do waht @martin-sweeny wanted (at least for Php-intellisense)
Php-intellisense need the language server available in basic php installation but not in docker, so i just needed to change the image to elixfbecker/php-language-server:latest : 
```#!/bin/sh

docker run \
    --rm \
    -i \
    --network=host \
    -v "$HOME":"$HOME":ro \
    -u $(id -u) \
    -w "$PWD" \
    elixfbecker/php-language-server:latest \
    php "$@"

return $?
```

I'm not sure it will work for the debug, but it seems to work for the autocompletion.

**Comment by judgej** [comment]
I am very interested in how I can get this working for a K8s pod too. I can wrap the K8s `exec` command to run a php command in a running pod, but have no control over the volume mappings. Doing search/replace on all the arguments passed in seems a bit clunky.

**Comment by lixaotec** [comment]
@martin-sweeny you-ve got it!

Do you have any workaround by now?

I use a docker php container, and windows with vscode .. how can i debug from my vscode and a remote docker container running linux.. (php code is locatead at a shared volume between docker and windows vscode)

thanks

**Comment by o-alquimista** [comment]
> @csmcgee Create a `/bin/sh` wrapper to your docker container and then point PHP Intellisense at the wrapper:
> 
> ```shell
> #!/bin/sh
> 
> docker run \
>     --network=host \
>     --rm \
>     -e HOME="$HOME" \
>     -u $(id -u):$(id -g) \
>     -v "$HOME":"$HOME" \
>     -w "$PWD" \
>     php:7-alpine \
>     php "$@"
> 
> exit $?
> ```
> 
> Please note you will need to map in any volumes you require, i've assumed your `$HOME` dir here.
> 
> ```json
> {
>   "php.executablePath": "/somewhere/php7wrapper",
>   "php.suggest.basic": false
> }
> ```
> 
> @felixfbecker Maybe you should shove this somewhere in your documentation?

I couldn't get this to work on Fedora with podman due to SELinux preventing the relabelling of the $HOME directory. Using the `--privileged` argument didn't work either.

**Comment by olivsinz** [comment]
Some other help here, so simple : https://medium.com/@jogarcia/vscode-access-to-php-docker-container-27ffc12b8e07
