### ISSUE TITLE
Question: installation and configurations

### ISSUE THREAD

**Issue by str** [felixfbecker/vscode-php-intellisense#159]
Installing and using this is not so straight forward, or at least I haven't found answers to my problems:

1. After installing the plugin in VSCode, should I go and ALSO install the php-language-server or does this plugin install the php-language server on it's own?

1. In a normal project, after installing a lot of vendors via composer, the amount of PHP files can be around +10K, and parsing them all will need around 10 minutes. So everytime I switch projects or start working, I loose around 10 mins just waiting for the initial parsing to finish.  Is this how it should work, or am I missing something?

1. The intellisense was useless, it took around 1 minute to show the suggestions. This changed after I disabled xdebug for the CLI and let it enabled only for the web server. Should the plugin notify the user via VSCode notifications that xdebug is enabled and that the intellisense for PHP will not work, disabling the plugin untill xdebug is turned off. (Or better yet, disable xdebug on runtime). This will be way better experience than thinking the plugin does not work.

1. The PHP-language-server says "After installing the language server and its dependencies, you must parse the stubs for standard PHP symbols **and save the index for fast initialization**".. but I never installed the language server, it looks like the plugin installed it itself. It does feel like I'm missing something because It takes way to loong for me to be able to start working in the project.

1. How to disable parsing folders? There should be a way to add folderst to ignore, per project by right clicking on a folder in vscode

**Comment by mdgiles** [comment]
I'm also confused by installation and configuration.  In my case nothing seems to be working, and despite setting php.suggest.basic to false I still seem to be getting only basic suggestions.  None of the advertised features such as Find All References, Go To Definition etc are appearing at all.  This makes me think I am missing some basic part of configuration.  I will watch this issue to see what is suggested and whether it helps me too.

**Comment by mdgiles** [comment]
I figured out the language server is crashing with UnexpectedValueException attempting to parse node_modules. Referencing your last point, there are a ton of issues out there already asking for the files.exclude setting to be honoured by the language server.

**Comment by felixfbecker** [comment]
1. no, it's bundled.
2. dependencies inside `/vendor/` are cached if a composer.lock is found.
3. XDebug should be disabled automatically https://github.com/felixfbecker/php-language-server/blob/0c399150a3e6349f0d1985c025bd099e3bb15206/bin/php-language-server.php#L35
  if not that might be a bug
4. The language server instructions are not relevant if you install the VS Code extension
5. That's not implemented yet, feel free to do a PR

**Comment by str** [comment]
@felixfbecker Thank you for your answers. I see my questions are recurrent issues created. Maybe updating the README file will help newcomers. 

I'll try to read the repo's code.
