### ISSUE TITLE
Goto def located a wrong file path

### ISSUE THREAD

**Issue by DarthPestilane** [felixfbecker/vscode-php-intellisense#160]
First, the program works fine.

The hover works fine too:
![image](https://user-images.githubusercontent.com/15375753/31367887-ddb4da94-ad3f-11e7-9a97-d8104be89eaa.png)

But when I pressed `cmd + click` to goto def, an error showed up. It said cannot find `path/to/xxx.php`. It's a wrong path that does not exist.
![image](https://user-images.githubusercontent.com/15375753/31368153-7aace61a-ad41-11e7-85a5-8c18c3dcc6e9.png)

I'm wondering whether it's a matter of cache... because I have moved the whole project before and the wrong path, as mentioned above,  was exactly the path of project before.

**Comment by felixfbecker** [comment]
Try to delete the cache (standard cache location per OS)

**Comment by DarthPestilane** [comment]
@felixfbecker Thanks but how to do that?

**Comment by felixfbecker** [comment]
As said it depends on your OS

**Comment by DarthPestilane** [comment]
@felixfbecker 

It's on MacOS.

I have removed the whole `vscode.app`, including `~/.vscode/`(extensions) and `~/Library/Application Support/Code/`.

I guess there was no cache then.

But after I  reinstalled `vscode` app and `php-intellisense` extension, the error was still there.

Please help.

**Comment by felixfbecker** [comment]
Delete `~/.phpls`

**Comment by DarthPestilane** [comment]
@felixfbecker Yes! It works! Thank you for your time, and hopefully it can have a command to do this job.
