### ISSUE TITLE
Find definitions

### ISSUE THREAD

**Issue by Pitu-pl** [felixfbecker/vscode-php-intellisense#161]
Hello

Im working on legacy code without namespace, with custom autoloader etc.

When in code methods are called from object like:
`$object = new Object();
$object->method();`

Jump to definition works fine.

I have problem with code like:
`$object = $this->get('ComponentTest');
$object->method();`

this `$this->get('Object')` load component from few directories.

Is possible to add custom configuration to help finding classes?

**Comment by felixfbecker** [comment]
To get IntelliSense on a return value of a method, the method needs an `@return` type annotation. An alternative is to add an `@var` annotation to `$object`. It is not possible to do this dynamically.

**Comment by Pitu-pl** [comment]
So I need to add annotation above object?
```
@var \path\to\Class
$object = $this->get('ComponentTest');```
yes?

My main problem is that I can't jump with cmd+left mouse to method. Example:
`$object = $this->get('ComponentTest'); $object->method();`
when I click cmd+left mouse on method loader show but can't find.

**Comment by felixfbecker** [comment]
what you posted is not valid syntax. Valid would be
```php
/** @var \ComponentTest */
$object = $this->get('ComponentTest');
```
