### ISSUE TITLE
Disable tab end line

### ISSUE THREAD

**Issue by hoangnamitc** [felixfbecker/vscode-php-intellisense#168]
Hellow everyone,

I try search but not result. Please help me how to disable pointer tab end line code:

DEMO

image
![image](https://user-images.githubusercontent.com/7042462/32255625-02049922-bedc-11e7-9fb7-606adf62fdec.png)

image
![image](https://user-images.githubusercontent.com/7042462/32255627-0574db58-bedc-11e7-9046-e7f0c88adc55.png)

image
![image](https://user-images.githubusercontent.com/7042462/32255629-08e7ed5c-bedc-11e7-99ee-368467aa6e17.png)

Thanks !

source:
https://github.com/Microsoft/vscode/issues/37201

**Comment by felixfbecker** [comment]
This is an emmet suggestion, not something from the PHP extension.
