### ISSUE TITLE
Comment show not new line

### ISSUE THREAD

**Issue by hoangnamitc** [felixfbecker/vscode-php-intellisense#169]
Hi Every one !

Please help me! 
How to hover into function, comment show exactly.

DEMO

![image](https://user-images.githubusercontent.com/7042462/32263653-7a68da8c-bf0d-11e7-9df5-67a362c2ad1c.png)

![image](https://user-images.githubusercontent.com/7042462/32263787-e9cd1b68-bf0d-11e7-920c-5893d5a4fe5b.png)

Thanks !

**Comment by felixfbecker** [comment]
Not sure what you expect, the way you wrote `$param1` it's just part of the description. Parameters are documented with `@param` in PHPDoc

**Comment by hoangnamitc** [comment]
My update:

![image](https://user-images.githubusercontent.com/7042462/32263900-7389e278-bf0e-11e7-9287-2532b67c0ce8.png)

![image](https://user-images.githubusercontent.com/7042462/32263929-91770112-bf0e-11e7-803c-0e70a9d18b9b.png)


Do not show Params :(

**Comment by felixfbecker** [comment]
You're looking for https://github.com/felixfbecker/php-language-server/issues/18

**Comment by hoangnamitc** [comment]
Oh, this feature missing :(

**Comment by di3663** [comment]
So it's still not work. Great !!!

I suggest using comment like this, at least know how to using functions
```
/**
  * array to xml
  * * @param array $array
  * * @param boolean $useXmlTag add tag `xml`
  * * @return string xml
  */
public function array2Xml($array, $useXmlTag = true) {
}
```


![3](https://user-images.githubusercontent.com/36250009/38767076-35d9e03c-400e-11e8-8149-c60a6d719ca1.png)

**Comment by angelpolitis** [comment]
For anyone still wondering, you can add a line break by entering two spaces at the very end of a line.

**Comment by JoKolov** [comment]
@angelpolitis Best answer ! Thanks for the tip.

It's working great in VScode.
