### ISSUE TITLE
php-intellisense not work

### ISSUE THREAD

**Issue by maruo34** [felixfbecker/vscode-php-intellisense#170]
At one point I just stopped working, I did not put any extensions.
What can be? How do I know what the problem is?

**Comment by felixfbecker** [comment]
Check the output channel, check the developer console, check whether the extension is still installed, ...

**Comment by maruo34** [comment]
extension installed and running.
output console clear
Where developer console?

**Comment by felixfbecker** [comment]
Help > Toggle Developer Tools.
What do you mean with "output console clear"? Is there an output channel for "PHP language server", or is it empty?

**Comment by maruo34** [comment]
![image](https://user-images.githubusercontent.com/24241732/32311615-a15270f2-bfaa-11e7-8d71-a8ab1edcc31f.png)
You mean this? "php.validate.executablePath": "C:/openserver7/openserver/modules/php/PHP-7-x64/php.exe"

**Comment by felixfbecker** [comment]
I cannot reproduce that error (`Class Composer\XdebugHandler not found`). It works fine for me.

**Comment by maruo34** [comment]
I do not understand so what's wrong?

**Comment by felixfbecker** [comment]
I don't know

**Comment by maruo34** [comment]
where you can download this class?

**Comment by felixfbecker** [comment]
It should be bundled in the extension (it is for me)

**Comment by MadHed** [comment]
http://php.net/manual/en/ini.core.php#ini.open-basedir

**Comment by maruo34** [comment]
Thanks, yes the protection from external access.

**Comment by Tony-Sol** [comment]
```
TypeError: mb_strlen() expects parameter 1 to be string, boolean given in C:\Users\myusername\.vscode\extensions\felixfbecker.php-intellisense-2.2.5\vendor\felixfbecker\language-server\src\ProtocolStreamWriter.php:72
Stack trace:
#0 C:\Users\myusername\.vscode\extensions\felixfbecker.php-intellisense-2.2.5\vendor\felixfbecker\language-server\src\ProtocolStreamWriter.php(72): mb_strlen(false)
#1 C:\Users\myusername\.vscode\extensions\felixfbecker.php-intellisense-2.2.5\vendor\felixfbecker\language-server\src\ProtocolStreamWriter.php(41): LanguageServer\ProtocolStreamWriter->flush()
#2 C:\Users\myusername\.vscode\extensions\felixfbecker.php-intellisense-2.2.5\vendor\sabre\event\lib\Loop\Loop.php(315): LanguageServer\ProtocolStreamWriter->LanguageServer\{closure}()
#3 C:\Users\myusername\.vscode\extensions\felixfbecker.php-intellisense-2.2.5\vendor\sabre\event\lib\Loop\Loop.php(233): Sabre\Event\Loop\Loop->runStreams(0)
#4 C:\Users\myusername\.vscode\extensions\felixfbecker.php-intellisense-2.2.5\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#5 C:\Users\myusername\.vscode\extensions\felixfbecker.php-intellisense-2.2.5\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#6 C:\Users\myusername\.vscode\extensions\felixfbecker.php-intellisense-2.2.5\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()

```
what is this suppose to be?

**Comment by jens1o** [comment]
@Tony-Sol please file a new issue, this looks like a bug
