### ISSUE TITLE
Format Document does not honor indentation using tabs

### ISSUE THREAD

**Issue by morganwdavis** [felixfbecker/vscode-php-intellisense#175]
With this extension, Format Document rebuilds the whole source file using fixed 4-character spaces, replacing tabs if that is the VSCode preferred settings.

**Comment by jens1o** [comment]
Ehm. Format Document will be removed with the next version, because of the reason you provided(and others)

See https://github.com/felixfbecker/php-language-server/issues/501

**Comment by felixfbecker** [comment]
Also a duplicate of https://github.com/felixfbecker/php-language-server/issues/343

**Comment by morganwdavis** [comment]
Oh... sorry.  And cool.  Is there a recommended alternative extension to get "Format Document" support for PHP?

**Comment by felixfbecker** [comment]
phpcs will give you the exact same formatting this extension had.
