### ISSUE TITLE
Format Document assumes particular style for curly braces

### ISSUE THREAD

**Issue by morganwdavis** [felixfbecker/vscode-php-intellisense#176]
With this extension, Format Document assumes a particular convention for placement of curly braces. Notably, in function declarations, the open brace is always positioned on the line below, flush left.  Whether  "correct" or not, this should be a setting to allow for whatever style convention is consistent with a project.

**Comment by felixfbecker** [comment]
@morganwdavis I already responded to you in #175 that formatting is going to me removed and if you read the README you'll see that this is the wrong repo to file this. Formatting was done by PHP CodeSniffer and you were always able to configure CodeSniffer with an XML config file.

**Comment by morganwdavis** [comment]
@felixfbecker Sorry... I missed all this fun.  Thanks for the clarification. I see phpcs requires a pear module installation plus the plugin for VSCode... sigh. Too bad its so messy. But I totally understand removing PHP formatting from your extension. I'd not want to have to support that either.

**Comment by felixfbecker** [comment]
I would like to support it through pretty printing our ASTs, but just passing the string contents to a third-party formatter with tons of bugs is a nightmare to maintain.

**Comment by felixfbecker** [comment]
You don't need to use pear. You can use `composer` too. Chances are you already have CodeSniffer installed as a devDependency to check formatting in CI.

**Comment by morganwdavis** [comment]
Understood. Thanks for the added details and the great work on this extension.
