### ISSUE TITLE
Format code option does nothing

### ISSUE THREAD

**Issue by aga5tya** [felixfbecker/vscode-php-intellisense#19]
Hi, first off thank you for the wonderful php intellisense plugin. 

I tried the format code option, but doesn't seem to show any effect on the file. Is there anything i am missing out on ?

Operation System: OSX
VS Code:  1.5.3
PHP Intellisense: 0.0.9

**Comment by felixfbecker** [comment]
It would help if you could show the file you are trying to format.

**Comment by aga5tya** [comment]
I tried it on a sample php files from the twig library trying to mess up the indentation. Doesn't work with that. Below is the link to a sample gist.

[Link](https://gist.github.com/aga5tya/176099a913ebed9b81565699cf58bd2e)

**Comment by felixfbecker** [comment]
![animation](https://cloud.githubusercontent.com/assets/10532611/19205089/9113b762-8ce0-11e6-96c9-48c923383a39.gif)

**Comment by MadHed** [comment]
@aga5tya 
I just tried the gist and everything worked as expected.
I have the same configuration as you, except that I am running Windows 10.

**Comment by felixfbecker** [comment]
Do you have any other PHP formatter installed?

**Comment by MadHed** [comment]
Did you select the text before formatting? That is a feature that is currently not supported by this plugin.

**Comment by aga5tya** [comment]
@felixfbecker I tried with a fresh copy of vs code with only intellisense plugin installed. Still does not work. Any specific logs i can share up? Are you on OSX ?

@MadHed I tried both ways, not sure what is causing the issue. Let me check on a linux OS and see if it works there.

![format-config](https://cloud.githubusercontent.com/assets/17351163/19210722/006f34b6-8d49-11e6-903e-f592534ccb82.gif)

**Comment by felixfbecker** [comment]
Don't highlight the code :)

**Comment by aga5tya** [comment]
@felixfbecker  Thank you! That solved it. I could not get it done earlier since some portion or variable was always highlighted in mine, But shouldn't this work with highlights as it would help me format only certain portion of the code as necessary and not everything at once always.

**Comment by felixfbecker** [comment]
It currently is very opinionated about where you should have empty lines and where not
https://github.com/felixfbecker/php-language-server/issues/29
https://github.com/felixfbecker/php-language-server/pull/35
