### ISSUE TITLE
basic php function suggestions don't show parameter explanations

### ISSUE THREAD

**Issue by cyrus86** [felixfbecker/vscode-php-intellisense#190]
unlike php.suggest.basic, this extension doesn't show the hover information for parameters of the functions in the suggestion dropdown, nor when the cursor is inside the function brackets.

php.suggest.basic: false
<img width="617" alt="" src="https://user-images.githubusercontent.com/2669027/32818743-591869fa-ca08-11e7-9bd0-3653e6c567f0.png">

php.suggest.basic: true
<img width="622" alt="" src="https://user-images.githubusercontent.com/2669027/32818900-81890b1e-ca09-11e7-92d6-e2efc4508946.png">

would great if it just showed the hover information alongside suggestions and inside function brackets as well.

**Comment by felixfbecker** [comment]
The sceenshots are the same?

**Comment by cyrus86** [comment]
wow you are quick. jut uploaded the other one
