### ISSUE TITLE
Code formatting does not work

### ISSUE THREAD

**Issue by timurmelnikov** [felixfbecker/vscode-php-intellisense#198]
When you press Ctrl + Shift + f, an error occurs. "Unfortunately, the formatting module for files 'php' is not installed."

**Comment by jens1o** [comment]
That's by purpose. The module has been removed as of 5.2

**Comment by louismariejoly** [comment]
@jens1o Do you know any other module for formatting php files by any chance ?

**Comment by gvigner** [comment]
Why was it removed ?

**Comment by jens1o** [comment]
Because of sooo many bugs and other bottlenecks(i.e. it wasn't easy to configure it)

**Comment by felixfbecker** [comment]
Please refer to the release notes.
https://github.com/felixfbecker/vscode-php-intellisense/releases/tag/v2.0.0
