### ISSUE TITLE
can't format document and error lint with Laravel file Console.php

### ISSUE THREAD

**Issue by adrianriyadi** [felixfbecker/vscode-php-intellisense#199]
I can't format document at all with this new release.. and always give lint error on Laravel Console.php file

**Comment by jens1o** [comment]
The ability of formatting documents has been removed as of the latest release.

**Comment by felixfbecker** [comment]
Please read the release notes https://github.com/felixfbecker/vscode-php-intellisense/releases/tag/v2.0.0
For your lint error, please file in the language server repo with some more details.
