### ISSUE TITLE
Message: "$this can only be used in an object context."

### ISSUE THREAD

**Issue by Gauss23** [felixfbecker/vscode-php-intellisense#201]
Hello,

we just wondered about a lot of "syntax"-errors in our code. The message is:

> $this can only be used in an object context.

Before your update to version 2.0.0 everything was fine. The files IntelliSense is now marking as wrong are config files, which are required/included in object context, so they are perfectly working. Of course IntelliSense cannot know that. Is there a chance to make this check optional?

Best regards,
Christopher

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#536
