### ISSUE TITLE
Bug on autocomplete

### ISSUE THREAD

**Issue by tom-schmitz** [felixfbecker/vscode-php-intellisense#207]
Can anyone tell me if this is a bug?

![bug](https://user-images.githubusercontent.com/22610955/33382165-42eaff62-d520-11e7-90be-a5e7d420e832.gif)

Every time when I press tab or click the autocomplete a backslash \ gets placed
in front of the result.

**Comment by julesgilson** [comment]
yep, me too - seems to have only just started happening... don't recall it before a few days ago.

**Comment by felixfbecker** [comment]
This is as designed. Marking global functions with `\` saves PHP a namespace lookup.

**Comment by haziq-danial** [comment]
hello, is there a solution for this?

**Comment by talesPGrechi** [comment]
> hello, is there a solution for this?

You should disable the setting "Intelephense › Completion: Fully Qualify Global Constants And Functions".
You can see it in the extension's settings
