### ISSUE TITLE
Ctrl + Click to Go To Definition

### ISSUE THREAD

**Issue by pierophp** [felixfbecker/vscode-php-intellisense#24]
It is possible to make Ctrl + Click works to Go To Definition like PHP Storm or Netbeans?

**Comment by felixfbecker** [comment]
This does work just fine

**Comment by razvanphp** [comment]
Nice one, but you should "market" it properly in the main description/gif, ex-Netbeans users cannot live without this. Thank you!

**Comment by felixfbecker** [comment]
Well on the technical side it is the exact same request VS Code sends to the language server, we can't even differentiate. Supporting one means supporting the other, in all language servers, not just this one
