### ISSUE TITLE
TCP socket can't be created on Linux

### ISSUE THREAD

**Issue by cardonator** [felixfbecker/vscode-php-intellisense#250]
Hello, I haven't been doing much PHP development for a couple of months and now this plugin doesn't seem to be working at all for some reason.

It seems like it probably broken in this commit: https://github.com/felixfbecker/vscode-php-intellisense/commit/ddddf2a178e4e9bf3d52efb07cd05820ce109f43

The behavior that I'm seeing is that it seems like the stream socket can't even be created. Developer Tools says:

```
ErrorException: stream_socket_client(): unable to connect to tcp://127.0.0.1:42679 (Connection refused) in /home/bj.cardon/.vscode/extensions/felixfbecker.php-intellisense-2.2.4/vendor/felixfbecker/language-server/bin/php-language-server.php:40
Stack trace:
#0 [internal function]: {closure}(2, 'stream_socket_c...', '/home/bj.cardon...', 40, Array)
#1 /home/bj.cardon/.vscode/extensions/felixfbecker.php-intellisense-2.2.4/vendor/felixfbecker/language-server/bin/php-language-server.php(40): stream_socket_client('tcp://127.0.0.1...', 111, 'Connection refu...')
#2 {main}
```

I also tried to run the language server manually from the command line, but that obviously wouldn't work:

```
~$ php vendor/felixfbecker/language-server/bin/php-language-server.php --tcp=127.0.0.1:8080 --memory-limit=4G
ErrorException: stream_socket_client(): unable to connect to tcp://127.0.0.1:8080 (Connection refused) in /code/vendor/felixfbecker/language-server/bin/php-language-server.php:40
Stack trace:
#0 [internal function]: {closure}(2, 'stream_socket_c...', '/code/vendor/fe...', 40, Array)
#1 /code/vendor/felixfbecker/language-server/bin/php-language-server.php(40): stream_socket_client('tcp://127.0.0.1...', 111, 'Connection refu...')
#2 {main}
```

**Comment by cardonator** [comment]
I figured out the issue here. I'm running PHP from inside a docker container, which works fine, but it can't connect to the plugin unless you have the network set to host.

It would be really great if this plugin supported running the language server in Docker and used the interpreter inside that container as well.

**Comment by felixfbecker** [comment]
It sounds like it _is_ supported, you just need to expose the network? How else would it work?

**Comment by cardonator** [comment]
What is not supported is running the language server inside a docker container. Since it has to run on the host and tries to open a TCP socket (as opposed to a file socket) to the language server from the PHP interpreter, the PHP interpreter has to be able to access ports open on the host network.

In my case, the PHP interpreter is running in a docker container and not natively on the host.

**Comment by felixfbecker** [comment]
Yes, but that is blocked by support to access file contents over LSP. The langserver has to read files from disk, in a docker container it would not have access to the files, at least not under the `rootUri` that VS Code sends it. See https://github.com/sourcegraph/language-server-protocol/blob/master/extension-files.md

**Comment by cardonator** [comment]
You would just mount the files inside the docker container, which is what I've done anyway for the interpreter. I'm not sure there is anything to do on this Issue anyway since in the end I figured out a workaround, which wasn't necessary when a file socket was being used but is necessary now that the language server has been switched to a TCP socket.

**Comment by felixfbecker** [comment]
Yes, you can mount them, but the file path in the container will not correspond to the file paths that VS Code sends over LSP.

**Comment by cardonator** [comment]
That is a much better explanation of the problem that is faced, however if the extension supported Docker then the problem could be addressed :)
