### ISSUE TITLE
Ignore folders for libraries

### ISSUE THREAD

**Issue by jaimerod** [felixfbecker/vscode-php-intellisense#26]
Add the ability to ignore folders that contain libraries. That way I don't get hundreds of warnings from somebody elses code.

**Comment by felixfbecker** [comment]
Ignore from indexing, or ignore from errors/warnings?

**Comment by jaimerod** [comment]
Ignore the errors/warnings because it is code we should not be changing. Is there a way of muting those warnings? It is a good idea to index them because those libraries are still going to be used in the application and intellisense should still work.

**Comment by toretto460** [comment]
I need also this feature to ignore some folders because i don't have read permissions.
Ex. I have a `.mysql` folder used to mount a docker volume and I receive the following error

```
[Error - 7:59:42 PM] Server initialization failed.
  Message: RecursiveDirectoryIterator::__construct(/project/.mysql/my_db_name): failed to open dir: Permission denied
  Code: -32603 
```

**Comment by simonrozsival** [comment]
+1

**Comment by d0x2f** [comment]
When using Composer, PHP-Intellisense simply fills my error box with hundreds of errors and warnings from third party dependencies in the vendor directory.

I think it shouldn't show errors from directories within the files.exclude vscode setting. That setting seems to align with this issue.

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#146
