### ISSUE TITLE
Stopped to work after VSCode upgrade

### ISSUE THREAD

**Issue by fernandoval** [felixfbecker/vscode-php-intellisense#271]
Hi,

This extension was working fine until the VSCode updated to v1.20.1. After that, the extension stopped to work completely.

No "go to definition", no "completion", no "signature help", no "workspace symbol", no "hover", no anything.

There is no error in output log extension host. And no entry in ouput select box.

I did try disable and enable again, uninstall and install again. But nothing solved the problem.

**Comment by felixfbecker** [comment]
I don't see any breaking changes in the release notes - if the extension broke between two vscode versions without any changes in the extension I would ask you to file this on the vscode repo as a bug

**Comment by jawittdesigns** [comment]
@felixfbecker there is something broken here. PHP intellisense is breaking the VSCode autocomplete functionality like for snippets (sort of). It seems to cause this 10-15 sec delay before the auto complete dialog opens for longer files(1000 lines). Disabling PHP intellisense fixes this delay.

Maybe this is being caused by the same issue that @fernandoval is having.

**Comment by felixfbecker** [comment]
@jawittdesigns that seems unrelated to what OP is describing.

**Comment by kerts93** [comment]
@felixfbecker doesn't work fore me also no longer.

Console log shows this:
![image](https://user-images.githubusercontent.com/4341091/36734758-23372156-1bdd-11e8-9bf8-888c0e47f173.png)

**Comment by kerts93** [comment]
Last update fixed the issue for me.

**Comment by ericlie** [comment]
hi @kerts93 how do you have your issue fixed?
i am using the php intellisense v.2.3.0
my php version v.7.2.0

I did encountered the same issues you had and installed node paackge "mz" and "semver"

and now 
```
Warning: require(C:\Users\asus\.vscode\extensions\felixfbecker.php-intellisense-2.3.0\vendor\composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in C:\Users\asus\.vscode\extensions\felixfbecker.php-intellisense-2.3.0\vendor\composer\autoload_real.php on line 66
```
I am thinking to install symfony though ..

**Comment by felixfbecker** [comment]
@ericlie please open a new issue
