### ISSUE TITLE
Go to Definition in PHPDoc comments 

### ISSUE THREAD

**Issue by razvanphp** [felixfbecker/vscode-php-intellisense#28]
Not sure how I can explain better, but this would be very useful, especially for private variables in classes.

Thank you for this great extension, makes VSCode perfect!

**Comment by felixfbecker** [comment]
I would love to support this, but I don't get any location info from phpDocumentor for the tags.

**Comment by razvanphp** [comment]
Maybe you can open a feature request issue there?

**Comment by felixfbecker** [comment]
https://github.com/phpDocumentor/ReflectionDocBlock/issues/87

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#134

**Comment by boer0924** [comment]
not work go to definition. 


![image](https://cloud.githubusercontent.com/assets/9416883/23979170/d32b5c52-0a32-11e7-9abc-c53b4e3269ba.png)

who can help me.
