### ISSUE TITLE
Refactoring support question

### ISSUE THREAD

**Issue by marcelloh** [felixfbecker/vscode-php-intellisense#283]
When I install this plugin, I see:
Advanced autocompletion and Refactoring support for PHP.

How does the refactoring part works?
I tried to find this on my own, but somehow was not able to find anything usefull.

I am looking to do this:

> Code refactoring is the process of restructuring existing computer code—changing the factoring—without changing its external behavior.

**Comment by leob** [comment]
I think this is on the "to do" list:

https://github.com/felixfbecker/vscode-php-intellisense#todo

I've googled for "VSCode PHP refactoring" (or 'rename') but nobody seems to have implemented it, yet. Really nobody. This is the only thing that would keep me from dropping Netbeans (which I currently use for PHP) in favor of VSCode.

**Comment by sandervanhooft** [comment]
Real refactoring support (pull up, etc.) would make me switch from phpstorm.

**Comment by felixfbecker** [comment]
Sorry for the confusion. I wrote that description a long time ago. Please read it as "this extension provides features that can help you refactoring" (e.g. find-all-references).
