### ISSUE TITLE
Blood Draining PHP Notification!

### ISSUE THREAD

**Issue by halukyamaner** [felixfbecker/vscode-php-intellisense#284]
![image](https://user-images.githubusercontent.com/8643150/37873363-30ab7cdc-3024-11e8-8c30-347b96ba4a16.png)

Hello.

Since the first day I am using VS Code and IntelliSense, I have this notification which I couldn't disable anyhow. The only way to avoid this notification is installating PHP to computer and defining to Settings. But I'm remote developer and I never have PHP environment on my computer.

It's draining my blood everytime I open VS Code and I'm unable to close this.

I have two questions on this case:

* Why I should to have PHP installed on my computer if I'm not using any debug or anything?
* Why it's impossible to close this notification while everyone is facing similar situations?

Please let me know a way of avoiding this.

**Comment by halukyamaner** [comment]
@MadHed I'm just using it for Auto Completion, rest I don't need any of features and extension works like charm without PHP.

I just want to get rid of this Notification which I had to click about thousands of time until today, there must be a way.

**Comment by jens1o** [comment]
> I just want to get rid of this Notification which I had to click about thousands of time until today, there must be a way.

Uninstall the extension. What you now have is the built-in support of vscode, not of this (advanced) extension.

**Comment by halukyamaner** [comment]
@jens1o I didn't ask your opinion mate :) I am looking for solution on my question, not your recommendation.

**Comment by halukyamaner** [comment]
Maybe, you are right. I just uninstalled, better I use less features and get rid of it.
