### ISSUE TITLE
PHP executable not found

### ISSUE THREAD

**Issue by espulgarin** [felixfbecker/vscode-php-intellisense#286]
Hello,

I'm getting this error message:
![errmode](https://user-images.githubusercontent.com/23417934/37877129-ef1d0b1c-301b-11e8-8969-a2d6ec855afc.PNG)

But my config has this line:
![root](https://user-images.githubusercontent.com/23417934/37877132-000648d0-301c-11e8-97c9-d3ec8aa028d2.PNG)

Can you told me, what I'm doing wrong?

I was looking in other sites but I couldn't find the mistake.

Thank you!

EDIT: The path is the correct, PHPis installed in that dir.

**Comment by MadHed** [comment]
the setting is just `php.executablePath`

**Comment by espulgarin** [comment]
Well, the problem is out. I didn't see that I had to delete "validate".

Thank you!
