### ISSUE TITLE
jump back from definition

### ISSUE THREAD

**Issue by NitsanBaleli** [felixfbecker/vscode-php-intellisense#29]
is it possible to add the ability to jump back to last definition?

**Comment by felixfbecker** [comment]
You mean going back to the reference? You can do that in VS Code with commands you might know from your browser, <kbd>Alt</kbd>+<kbd>⬅️</kbd> or a back button on your mouse will jump back.

**Comment by NitsanBaleli** [comment]
Im sorry, is this a behaviour built in or needs to be added?
trying the methods you suggested didn't do anything

**Comment by felixfbecker** [comment]
That is built in into VS Code. It is also something I can't even control, so I'm gonna close this

**Comment by felixfbecker** [comment]
![animation](https://cloud.githubusercontent.com/assets/10532611/20037502/907b6a78-a420-11e6-892f-06a8e72b7934.gif)
