### ISSUE TITLE
Is it possible, when you double click on a variable to include the dollar sign?

### ISSUE THREAD

**Issue by darcome** [felixfbecker/vscode-php-intellisense#295]
Hi everyone,

Is it possible, when you double click on a variable or when you CTRL + SHIFT + (left or right arrow) to select it, to include the dollar sign? I often do it to copy paste variables, and it would be usefull to copy paste the dollar sign too.

If it is already possible, can you tell me what I am doing wrong?

Thanks in advance.

**Comment by felixfbecker** [comment]
That functionality is provided by vscode afaik, please file an issue there
