### ISSUE TITLE
Error spawning PHP: spawn EACCES and Ubuntu

### ISSUE THREAD

**Issue by JonGarbayo** [felixfbecker/vscode-php-intellisense#297]
Hi!

I know this kind of issues are already closed or resolved, but I can't make it work on my Ubuntu 16.04 :(

Using the ``"php.executablePath"`` setting, I tried to put the PHP7 installation (that I downloaded from the official PHP website) on multiple paths, like the ``C:`` root, in ``/usr/bin/``, in ``/home/MYUSERNAME/bin``.

For every path, I tried a ``chown`` with my username and a ``chmod 777``, but the result is the same: ``Error spawning PHP: spawn EACCES``.

Could you help me to solve this issue?

**Comment by felixfbecker** [comment]
What do you mean eith the C: root? Are you using Windows or Linux?

**Comment by JonGarbayo** [comment]
Sorry, as I am a Windows user originally, I said C: to talk about the system drive x)

But in this case I am on Ubuntu.

**Comment by JonGarbayo** [comment]
It's more complicated.

Me and my team are working on a PHP 5.6 app. So all of our machines are running this version.
As I want to use PHPIntellisense, I want to tell it where is the PHP7 folder I downloaded from php.net.

There is no ``.php`` file in this folder. Maybe I have to compile it? I'm new to the Linux world, so I don't really know.

**Comment by MadHed** [comment]
Since you are using ubuntu, you should be able to install php7 via apt, no?

`sudo apt install php`

**Comment by JonGarbayo** [comment]
Yes I could.
But won't it interfere with my 5.6 install?

**Comment by JonGarbayo** [comment]
Well, I found this page: [https://www.tecmint.com/install-different-php-versions-in-ubuntu/](How to Install Different PHP (5.6, 7.0 and 7.1) Versions in Ubuntu).

I will follow these instructions when I will have some time. I will come back here to tell how it worked or not :)

**Comment by JonGarbayo** [comment]
It worked!

After following the instructions, I had to specify ``"php.executablePath": "/usr/bin/php7.2"`` in my VS Code settings. But now it works, and I didn't break my PHP 5.6 app :)

For future reference, just in case this article could be deleted, here are the main steps:
- add the Ondřej Surý PPA:
``sudo add-apt-repository ppa:ondrej/php``
- Install PHP7:
``sudo apt install php7.x`` (replace x by 0, 1 or 2, depending on what you need)
- Set PHP5.6 as default PHP version:
``sudo update-alternatives --set php /usr/bin/php5.6``

You will also need some other commands for your HTTP server, and some ``sudo apt update`` but that's another story.

Thanks for your help!
