### ISSUE TITLE
CPU overloading...

### ISSUE THREAD

**Issue by yarcowang** [felixfbecker/vscode-php-intellisense#31]
Thanks for your efforts for doing this extension, but I get a high CPU overloading... And even, it will fork another process named `PHP` in some cases.

Here is the processes:
```
yarco           59482  60.9  1.0  2535072  80160   ??  R     2:27下午   1:10.99 php /Users/yarco/.vscode/extensions/felixfbecker.php-intellisense-0.0.11/vendor/felixfbecker/language-server/bin/php-language-server.php
yarco           59260  60.4  1.4  2572720 117184   ??  R     2:06下午  12:59.76 php /Users/yarco/.vscode/extensions/felixfbecker.php-intellisense-0.0.11/vendor/felixfbecker/language-server/bin/php-language-server.php
yarco           31199  58.8  0.1  2486664   5448   ??  R     2:33下午  72:15.42 php /Users/yarco/.vscode/extensions/felixfbecker.php-intellisense-0.0.11/vendor/felixfbecker/language-server/bin/php-language-server.php
```

**Comment by felixfbecker** [comment]
It should only spawn one process, the language server. CPU usage will be quite high while the server indexes your process. You can see the process of that in the output panel.
If there are multiple processes that could mean there was an error, VS Code restarts it but the old server is not killed correctly. Try to see if Help > Toggle Developer Tools gives you any error messages.

**Comment by yarcowang** [comment]
Hi, after i toggle on the develops tools, i see a lot of messages from:
`file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js`

**Comment by felixfbecker** [comment]
That is totally expected, it just logs the communication. It's only interesting if it's red

**Comment by yarcowang** [comment]
I think I may find the problem, but I don't understand, I've already set `vendor/` directory to be ignored...but workbench.main.js still go through a lot of files under that directory
```
 "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/node_modules/**": true,
    "**/vendor/**": true
  },
```

**Comment by felixfbecker** [comment]
That setting is not used by the server in any way, it searches the workspace for PHP files itself.

**Comment by yarcowang** [comment]
So how to ignore them?
I think the reason is there are a lot of PHP files under the `vendor/`... 
And I see there are some settings in the php-language-server.php:
`ini_set('memory_limit', $options['memory-limit'] ?? -1);`
So how to limit the CPU usage?

```
[Extension Host] Content-Type: application/vscode-jsonrpc; charset=utf8
Content-Length: 178

{"method":"window\/logMessage","params":{"type":3,"message":"Parsing file 882\/11839: vendor\/behat\/transliterator\/src\/Behat\/Transliterator\/data\/xfc.php."},"jsonrpc":"2.0"}Content-Type: application/vscode-jsonrpc; charset=utf8
Content-Length: 253

{"method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/Users\/yarco\/Documents\/projects\/jobs\/newband\/newband-apiv2\/nbapp\/vendor\/behat\/transliterator\/src\/Behat\/Transliterator\/data\/xfc.php","diagnostics":[]},"jsonrpc":"2.0"}
```

**Comment by yarcowang** [comment]
Mac OS: 10.10.5
VSCode: 1.7.1
PHP: 7.0.10
Symfony 3

**Comment by felixfbecker** [comment]
I think what you are looking for is either caching or ignoring files. Please see

https://github.com/felixfbecker/php-language-server/issues/141
https://github.com/felixfbecker/php-language-server/issues/121

**Comment by yarcowang** [comment]
I see.
