### ISSUE TITLE
Error: Cannot find module 'mz/child_process'

### ISSUE THREAD

**Issue by WichardRiezebos** [felixfbecker/vscode-php-intellisense#312]
The language server cannot be started since I get this error in the developer console:

`Error: Cannot find module 'mz/child_process'`

**Comment by felixfbecker** [comment]
Weird, since what version? Does an older version work for you?

**Comment by WichardRiezebos** [comment]
Well, the weird thing is. Yesterday it worked totally fine. I didn't even update NodeJS or VSCode.

**Comment by WichardRiezebos** [comment]
I resolved it by removing the extension folder located at `%userProfile%/.vscode/extensions` and re-installing it again.
