### ISSUE TITLE
go to definition doesn't work

### ISSUE THREAD

**Issue by visualhu** [felixfbecker/vscode-php-intellisense#32]
I installed the latest version(0.0.11), go to definition doesn't work.

// Place your settings in this file to overwrite the default settings
{
    "php.validate.executablePath": "C:/php56/php.exe",
    "php.executablePath":"C:/php56/php.exe"
}

**Comment by felixfbecker** [comment]
You have to give a bit more information.
Do you have output under "PHP Language Server" in the output panel? If yes, what?
Are there errors in the console under Help > Toggle developer tools?
What code symbol did you try go to definition on?

**Comment by mniewrzal** [comment]
From paths it looks that you are trying to use PHP 5.6, maybe this is a problem. PHP LS needs PHP 7.

**Comment by felixfbecker** [comment]
Normally that should cause an error message though
