### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by nadar** [felixfbecker/vscode-php-intellisense#321]
Hi, maybe i am in the wrong repo but i was not able to find out if its a "missing" feature by design, a wrong configuration or just related to vscode. 

I was trying out vscode several times but code completion does not work as expected or as i already mentioned it was never be intended to work like this:

Assuming i have 2 files not in the same directory, but in the same namespace:

foo/Foo1.php:

```php
namespace foo;

class Foo1
{

}
```

foo/bar/Bar1.php:

```php
namespace foo/bar;

class Bar1
{

}
```

the code completion is not able to detected the `Bar1` class when typing in `Foo1`. For my understanding of code completion it should be possible to find all classes inside the current work directory while typing. After selecting the class it will be written to use statement section. This is what Eclipse PDT, PHPStorm or others does. 

If i have two files in the same directory, the suggestion works but only for files in the same directory.

So i am just wondering if this feature not implemented, does not work on my machine or any other reason? I tested on OSX and Ubuntu 18.10 with latest VSCODE and intellisense extension, also trying to configure the path to the php bin file and disable default completion. For example Eclipse PDT does have an indexing process, afterwards all classes are available (also from vendor folder).

**Comment by valerio-brew** [comment]
https://github.com/felixfbecker/php-language-server/issues/513

**Comment by felixfbecker** [comment]
@nadar the language server will look at all subfolders in the workspace, but does not support multiple workspace folders. Are you using multiple workspace folders? Can you give an example where exactly your cursor was when typing `Foo1`?

@valerio-brew I actually started a WIP PR that I never had the time to finish: https://github.com/felixfbecker/php-language-server/pull/509
It's along those lines - look at all `workspaceFolders` for indexing and make sure to consider all `composer.json`/`composer.lock`s.

**Comment by nadar** [comment]
@felixfbecker I made a quick gif for you => http://www.giphy.com/gifs/1dOKUo82Sfjihom8hg

+ Auto complete suggestion is displayed if already in use statement.
+ Auto complete suggestion works if in the same namespace.

If file is located in another namespace or directory (in vendor like in the gif the Curl class which is located in vendor as you can see) it does not work.

Does that help? Maybe i can provide some more informations?

**Comment by felixfbecker** [comment]
That is as designed. Auto completion suggests you things that are in scope

**Comment by nadar** [comment]
Hmm okay, sad. But since composer and vendor folder is so important it would maybe be a good to provide full auto completion so it can compete with PHPStorm, Eclipse PDT and others.

So i am going to close this issue 😢

**Comment by valerio-brew** [comment]
Hi Felix,

I've been trying to workaround the limitations, for mac and linux you can
create different workspace dummy folders, than symlink all projects folders
into the dummy folder, does work unfortunately has weird effects on
gitlens, but I  more than happy to gove away git automation.

works fairly well, except that indexing takes a bit more time.

I've seen your patch, but to be of any help I need to understand how
interaction between vscode and language server works, not much spare time
to develop while I am managing my team :/

I'll try to fix this as I would like to have my whole team to work on
vscode, as I said your php code is so elegant that I almost fell in love
worh you xD

**Comment by felixfbecker** [comment]
@nadar I think you are looking for https://github.com/felixfbecker/php-language-server/issues/234

@valerio-brew thanks, I am happy to help give an overview of how this works, feel free to contact me on Gitter (https://gitter.im/felixfbecker/php-language-server or DM me)
