### ISSUE TITLE
Config for specifying vendor directory.

### ISSUE THREAD

**Issue by hworld** [felixfbecker/vscode-php-intellisense#33]
In the language server project it says: "Errors/Warnings from the vendor directory are ignored."

Would be great to have a way to specify either a different directory, or multiple directories. Right now my composer.json has this:

```
"config": {
	"vendor-dir": "library"
},
```

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#164

**Comment by hworld** [comment]
Whoops, sorry. Didn't know where config requests should go since it's somewhat related to vs code settings. 👍
