### ISSUE TITLE
Requires PHP 7?!

### ISSUE THREAD

**Issue by skyvondave** [felixfbecker/vscode-php-intellisense#331]
We're using PHP 5.x... not going to use 7; that isn't my decision.

I just installed the extension yet I keep getting this notification: "You need at least PHP 7 installed for the extension to work. You can either add it to your PATH or set the php.executablePath setting."

It doesn't matter what I do nor which instructions I follow. Web search threads show no steps forward to just have it use my existing Mac's PHP 5.6 installation in /usr/bin/php with no warning even though I set that path to `php.executablePath` in User settings.

**Comment by felixfbecker** [comment]
The language server cannot run without PHP 7, it uses PHP 7 features. It is impossible to run with PHP 5.6.

**Comment by skyvondave** [comment]
Strange, most companies I've worked at in the last 5 years used at least PHP 5.x, very few used 7.

I'm not understanding why 5.x is not supported.

Will upgrading my Mac to PHP 7 allow for backwards-compatibility with the extension with 5.x?

**Comment by bblori** [comment]
I am using php 7.2 but still I got this warning, "The language server needs at least PHP 7.1 installed. Version found: 5.6.30" any solution to disable?
I set the following
You have chosen not to receive recommendations for this extension it is set.
json, "php.suggest.basic": false, added
