### ISSUE TITLE
Huge parsing CPU load (cache?)

### ISSUE THREAD

**Issue by muuvmuuv** [felixfbecker/vscode-php-intellisense#340]
I don't know if it is possible, but it would likely better to cache all parsed files somewhere rather then parsing them on every VSCode startup. I have an installation of over 20k files and it takes so much time to parse all of them, a cache what reduce that load time.

Just tell me if there is a solution for some kind of that or if I should post this issue to the php-language-server. Not really sure where it belongs too.

**Comment by benyaminl** [comment]
> I don't know if it is possible, but it would likely better to cache all parsed files somewhere rather then parsing them on every VSCode startup. I have an installation of over 20k files and it takes so much time to parse all of them, a cache what reduce that load time.
> 
> Just tell me if there is a solution for some kind of that or if I should post this issue to the php-language-server. Not really sure where it belongs too.

It's already implemented  on https://github.com/bmewburn/vscode-intelephense. Just use it.
