### ISSUE TITLE
phpcs:enable / phpcs:disable / phpcs:ignore  not working

### ISSUE THREAD

**Issue by emveeoh** [felixfbecker/vscode-php-intellisense#343]
PHPCS (PHP Code Sniffer) lint integration does not seem to pass ignore-this-line-of-code requests to VSCode. After adding the ignore request to the code in error, the page is still showing problems and are being marked in RED in VSCode. 

Not working:
// phpcs:ignore
// phpcs:disable
// phpcs:enable

Neither of these examples work:

    // phpcs:disable
        array_unshift($to_add, &$this->_array); 
    // phpcs:enable

OR

        array_unshift($to_add, &$this->_array); // phpcs:ignore

**Comment by felixfbecker** [comment]
PHP CS is not used in this extension.
