### ISSUE TITLE
Feature Request: Go to/list references when CTRL+CLICK the definition of the method

### ISSUE THREAD

**Issue by echonox** [felixfbecker/vscode-php-intellisense#358]
Feature Request

In PHPStorm when you hold CTRL and click a reference of a method you go to the definition of the method (This already works in vscode), and when you hold CTRL and click the definition of the method you either go directly to the reference of the method (if there is one) or you get a list of references (not working in vscode), could we have this in vscode?

**Comment by felixfbecker** [comment]
This needs to be implemented in VS Code, not the language server.
