### ISSUE TITLE
Go to definition not work - for two folders with same class, always lookup class in workspace folder 1

### ISSUE THREAD

**Issue by johnnytemp** [felixfbecker/vscode-php-intellisense#360]
I have two workspace folder folder1 & folder2 with same class "classes/Api.php".  When I'm inside a file folder2/public/controllers/manageSth.php and I want to "go to definition" for this code:

    Api::method2()  // static function method2() is only in folder2/classes/Api.php's Api class

It shows `No definition found for method2`.  If I re-order the workspace folder to folder2 then folder1, it can jump.

Please when in file `folder2/public/controllers/manageSth.php`, it should use the definition in the right workspace folder first.

Thank you.

**Comment by johnnytemp** [comment]
And may it look up from both two classes, instead of just one? (lower priority feature request than the above)

i.e. in `Api::method2()` of `folder2/public/controllers/manageSth.php`, look up from folder2/classes/Api.php then folder1/classes/Api.php, because folder1 might be an included library.

**Comment by felixfbecker** [comment]
Multiple workspaces are not supported yet. See https://github.com/felixfbecker/php-language-server/issues/513

**Comment by vibranttheme** [comment]
> 

> dfsdfsf

**Comment by vibranttheme** [comment]
From one class defination to another class defination not working....
