### ISSUE TITLE
VS Code

### ISSUE THREAD

**Issue by francesco-pierangeli** [felixfbecker/vscode-php-intellisense#373]
- Extension Name: php-intellisense
- Extension Version: 2.3.5
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
  "activationTimes": {
    "startup": false,
    "codeLoadingTime": 128,
    "activateCallTime": 10,
    "activateResolvedTime": 293,
    "activationEvent": "onLanguage:php"
  }
}
```

**Comment by felixfbecker** [comment]
Please provide a description of the issue
