### ISSUE TITLE
"Go to Definition" needs to be improved

### ISSUE THREAD

**Issue by Yurunsoft** [felixfbecker/vscode-php-intellisense#38]
PHP IntelliSense is very good.But "Go to Definition" needs to be improved.
Look this code:

```
class ParentItem
{
    public function test()
    {
        echo 'test';
    }
}
class Child extends ParentItem
{
    
}
$a = new Child;
$a->test();
```

I can't go to definition`$a->test()`

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/issues/169
