### ISSUE TITLE
Clear errors on file closed

### ISSUE THREAD

**Issue by jmfederico** [felixfbecker/vscode-php-intellisense#381]
Hi

When a file that had errors or warning is closed on VSCode, this extension does not clear/clean the errors for that file, generating a lot of noise.

Sometimes you can't fix a file on a project, but you still have to open it to examine it. It then hangs as a file with errors until you close the editor and open it again.

Would be great if the extension could clear the error log for closed files.

**Comment by felixfbecker** [comment]
The extension doesn't just show errors, it shows errors for all files in the open folder. This is as designed.

**Comment by jmfederico** [comment]
Can this be implemented as an option?

See how PHPMD implemented it

https://github.com/sandhje/vscode-phpmd/pull/39/commits/114476d2582ad89124ce32b09a03db14aac3a4e3

I mention it because it does generate noise. Some files you can not fix,

**Comment by jmfederico** [comment]
Ok, now I understand.

I think my problem is now related to https://github.com/felixfbecker/php-language-server/issues/164

Thanks! Great projects by the way.
