### ISSUE TITLE
forever installing

### ISSUE THREAD

**Issue by k9282000** [felixfbecker/vscode-php-intellisense#4]
I install this extension all day
but always installing,why....

VS code 1.3.1
OS: win7
![image](https://cloud.githubusercontent.com/assets/3058883/18244378/5eb1a21e-7392-11e6-8e70-114ae9931b50.png)

**Comment by felixfbecker** [comment]
I just installed the extension and it only took a few seconds - there must be something wrong with your system or internet connection. Maybe try to reinstall Code.
