### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by riskidev** [felixfbecker/vscode-php-intellisense#408]
- Issue Type: `Performance`
- Extension Name: `php-intellisense`
- Extension Version: `2.3.10`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/andriyanto/felixfbecker.php-intellisense-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Nemi5150** [comment]
I have this problem with the extension, but the link to "find more details here" no longer works. How do I fix this problem?
