### ISSUE TITLE
Intellisense shown on the popup not formatted

### ISSUE THREAD

**Issue by takato1314** [felixfbecker/vscode-php-intellisense#412]
Hi,
Just some minor bug here, but it would be nice if it can be fixed.
![image](https://user-images.githubusercontent.com/10910968/52192791-d3768780-2886-11e9-8146-2066ada4cdb9.png)

As shown above, the html part of the intellisense does not format properly in the vscode.  The following are the VSCode info I am using:

Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by felixfbecker** [comment]
https://github.com/Microsoft/vscode/issues/40607
