### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined constant 'STDERR'

### ISSUE THREAD

**Issue by ing4prg** [felixfbecker/vscode-php-intellisense#416]
When Visual Studio Code 1.31.1 is opened, this error is throw:

=========================================

PHP Fatal error:  Uncaught Error: Undefined constant 'STDERR' in C:\Users\...\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\src\StderrLogger.php:23
Stack trace:
#0 C:\Users\...\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\psr\log\Psr\Log\AbstractLogger.php(55): LanguageServer\StderrLogger->log('critical', 'Error: Call to ...', Array)
#1 C:\Users\...\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\bin\php-language-server.php(31): Psr\Log\AbstractLogger->critical('Error: Call to ...')
#2 [internal function]: {closure}(Object(Error))
#3 {main}
  thrown in C:\Users\...\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\src\StderrLogger.php on line 23

Language server exited with exit code 255

=========================================

Any idea why and how to fix it?
Thanks!

**Comment by felixfbecker** [comment]
This is a problem with your PHP. `STDOUT` is a built-in constant. http://php.net/manual/en/features.commandline.io-streams.php

**Comment by tolik518** [comment]
`STDERR` is only available in php cli, but not in php fpm.
