### ISSUE TITLE
Tooltip formatting

### ISSUE THREAD

**Issue by moseleyi** [felixfbecker/vscode-php-intellisense#439]
When hovering over a function the formatting isn't interpreted as HTML: 

```<p>For objects, if you have SPL installed, you can hook into count() by implementing interface {@see \Countable}. The int```

In here the `<p>` tag is not interpreted. Looks a little bit buggy, doesn't it?

**Comment by netifork** [comment]
i have the same problem , hope it will be fixed :D
![](https://i.ibb.co/TbbhrwQ/Shared-Screenshot.jpg)

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/40607, https://github.com/felixfbecker/php-language-server/issues/674
