### ISSUE TITLE
language sever incompatible for >php7.1

### ISSUE THREAD

**Issue by chopins** [felixfbecker/vscode-php-intellisense#445]
when php version greater than 7.1, intelephense will trigger `DEPRECATED` Error
because ReflectionType::__toString() is DEPRECATED
**So fixed below:** 
1. In file `felixfbecker.php-intellisense-2.3.10/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php` line `127`
change below code:
```php
//line 127
$class = (string)$param->getType();
```
to
```php
$paramType = $param->getType();
if(PHP_MAJOR_VERSION > 7 || (PHP_MAJOR_VERSION >=7 && PHP_MINOR_VERSION >= 1)) {
      $class = $paramType->getName();
 } else {
       $class = (string)$paramType;
 }

```
2. in file `felixfbecker.php-intellisense-2.3.10/vendor/netresearch/jsonmapper/src/JsonMapper.php` line `300`, 
change below code:
```php
if ($type !== '' && $type{0} != '\\') {
```
to 
```php
if ($type !== '' && $type[0] != '\\') {
```

**Comment by felixfbecker** [comment]
Should be fixed in latest version
