### ISSUE TITLE
Not correctly interpreting PHP version.  Thinks PHP 7.1.0 is PHP 5.6.26

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/vscode-php-intellisense#47]
_From @Maelstorm1973 on January 18, 2017 11:57_

PHP Version:
```
C:\Servers\php>php --version
PHP 7.1.0 (cli) (built: Dec  2 2016 05:24:57) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```
VS Code Settings:
```
// PHP settings
"php.validate.enable": true,
"php.validate.executablePath": "C:\\Servers\\php\\php.exe",
"php.validate.run": "onType"
```

The error that I am getting is as follows:

**ERROR**  The language server needs at least PHP 7 installed. Version found: 5.6.26

I can guarantee you that there is no PHP 5.6 installed anywhere on this machine.

_Copied from original issue: felixfbecker/php-language-server#242_

**Comment by felixfbecker** [comment]
`php.validate` is _not_ for this extension, that is the built-in validation.
Set `php.executablePath` like described in the README or make sure the version in your PATH is PHP 7.

**Comment by oojacoboo** [comment]
@felixfbecker It'd be nice if this setting was added to the default config.  There is only `php.memoryLimit` currently.  And, `php.executablePath` throws an alert of "Unknown configuration setting".

http://files.jacobt.com/mY9tgDTZr4

**Comment by jens1o** [comment]
That would be fixed as soon as there is  a new release.

**Comment by devtekve** [comment]
For anyone having this issue, it is due the PATH, you must change your environment PATH. 
on Linux: nano ~/.bash_profile
On Windows: Edit environment Variables -> System Variables -> Path. Change the priority
![vscodeerror](https://cloud.githubusercontent.com/assets/7696966/26662864/f10dd390-4654-11e7-9d12-be0672064a12.png)

**Comment by bujashaka** [comment]
I can confirm none of the above works for me. Your program is unable to read the PATH variable or the user config file. Screenshot included. Also i have tried all possible variations of slashes. /, //, \, \\ 
![intellisense_error](https://user-images.githubusercontent.com/32610630/31315441-6d977768-ac21-11e7-9973-2ad23c4bf49e.jpg)

**Comment by felixfbecker** [comment]
What's your output of `C:\wamp64\bin\php7.0.10 --version`?

**Comment by felixfbecker** [comment]
The error in your screenshot is not about the wrong version, it is about not finding the php binary at all.

**Comment by bujashaka** [comment]
OK, problem solved. It's not abouth pointing where php7 is, that was correct. I downloaded same php version BUT this time it's independent, not part of WAMP. NOTHING else changed but separating php7 to C:/php7/php.exe and it works!

**Comment by bujashaka** [comment]
the longer you fight with trying to solve a problem the better it feels after you find the solution!
