### ISSUE TITLE
How is the extension installing the PHP Language server

### ISSUE THREAD

**Issue by gauravmak** [felixfbecker/vscode-php-intellisense#473]
Maybe I am missing something very basic here. I checked the extension code to see how exactly it is specifying the dependency of the PHP language server but could not find it.

[This line](https://github.com/felixfbecker/vscode-php-intellisense/blob/438ced4ff261ea7b6f7ecb8a55b464242466430d/src/extension.ts#L86) does specify the path to the PHP file but I could not find where `composer install` is even run before that to have PHP Language Server files into the vendor directory.

Can anyone please point that out? Thanks.

**Comment by gszy** [comment]
On the [Releases](https://github.com/felixfbecker/vscode-php-intellisense/releases) page there are links to the compiled `.vsix` files that we can use to install the extension. If you unpack (unzip) one of these files, you’ll find that the `vendor` directory is already there. So I guess `composer install` is run as part of the release process. It may be [this thing](https://github.com/felixfbecker/vscode-php-intellisense/blob/v2.3.14/.travis.yml#L29), but it may be some other maintainer’s script as well.

> I checked the extension code to see how exactly it is specifying the dependency of the PHP language server but could not find it.

https://github.com/felixfbecker/vscode-php-intellisense/blob/v2.3.14/composer.json#L10

**Comment by gauravmak** [comment]
Thanks for your help @gszy I appreciate this.
