### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by zangai** [felixfbecker/vscode-php-intellisense#5]
I'm getting the following notification on top:
`The PHP Language Client server crashed 5 times in the last 3 minutes. The server will not be restarted.`

My output window shows:
```
[Info  - 5:49:53 PM] Connection to server got closed. Server will restart.
[Info  - 5:49:53 PM] Connection to server got closed. Server will restart.
[Info  - 5:49:53 PM] Connection to server got closed. Server will restart.
[Info  - 5:49:54 PM] Connection to server got closed. Server will restart.
[Error - 5:49:54 PM] Connection to server got closed. Server will not be restarted.
```

EDIT: Just noticed that you closed issues relating to these problems while mentioning the WIP state. However, this extension is publicly available, and it is not mentioned it doesn't work out-of-the-box.

**Comment by felixfbecker** [comment]
It is highlighted though that this is a work-in-progress, it is labeled as _preview_ and its version is not stable (0.x) so you should expect missing features, bugs and crashes 😉 
It is also mentioned that bug reports typically should go to the language-server repo.

That being said though, the limited features that are available should work. I just tested the latest version and it doesn't crash for me. The language server build is passing and coverage is at 90%.

It may be special to your environment or project. Are you running PHP 7? Have you tried it with a simple PHP file?
Could you clone the repo and run the extension from source to get the STDERR output of the language server?

Of course, if you feel the readme could be improved feel free to do a PR.

**Comment by zangai** [comment]
Fair enough, I actually had to mention that to justify me creating another issue about it. You were right though, I was running PHP 5.6 for fear of incompatibility with my other projects. It seems to work now. 

It wouldn't be a bad idea to mention the requirement of PHP 7 in the README :)

Thanks for your response.
