### ISSUE TITLE
Error parsing PHP version. Please check the output of php --version

### ISSUE THREAD

**Issue by nicollaas94** [felixfbecker/vscode-php-intellisense#50]
I'm having Error parsing PHP version. Please check the output of php --version

but i'm with php 7.0.6

C:\> php --version
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0

Warning: Module 'openssl' already loaded in Unknown on line 0
PHP 7.0.6 (cli) (built: Apr 28 2016 14:12:14) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

**Comment by felixfbecker** [comment]
This is because of the warning and fixed by #46
