### ISSUE TITLE
Installation issues...

### ISSUE THREAD

**Issue by mjoksa** [felixfbecker/vscode-php-intellisense#51]
Hi,

It was long time ago I had to do any PHP coding and lot has changed since then (I use NET in my everyday development) and now I have some small PHP project to attend to, so I decided to use VS Code to help me with PHP. 

First thing I did is to install PHP Debug (thank U for this extension too) and made it work pretty fast. Now I can debug PHP code :)

During my PHP development sessions, I saw that there is no VS code PHP intellisense for MySQL objects (in specific mysqli), so I decided to try your other extension - PHP Intellisense and I failed :(

After I installed extension, I can see format code option in context menu, but no matter what I tried I could not see any intellisense regarding MySQL PHP objects.

Here are my settings:
`"php.validate.executablePath": "C:/xampp/php/php.exe",
"php.validate.run": "onType",
"php.validate.enable": false`

I tried "php.executablePath" too, without and in combination with "php.validate.executablePath" but it did not seem to work. As U can see, I am using XAMPP with PHP 7.0.13 (cli) (built: Nov  8 2016 13:45:28) ( ZTS ) (PHP is in my PATH too).

Based on all said in READ.me I was not sure if I need to install PHP language server in order to make intellisense work so I did not install it :)

Is there anything else that I can do/try in order to get PHP MySQL objects intellisense to work?

Thanks

**Comment by felixfbecker** [comment]
Autocompletion is currently supported by the language server but not released in the VS Code extension yet because of https://github.com/Microsoft/vscode/issues/9003
