### ISSUE TITLE
Please add support for PHP 8.0

### ISSUE THREAD

**Issue by buismaarten** [felixfbecker/vscode-php-intellisense#510]
Sometimes VS Code shows a notification that some ReflectionParameter functionality is deprecated, happening since I upgraded my MacBook to PHP 8.0

```
ErrorException:
Method ReflectionParameter::getClass() is deprecated in /Users/buismaarten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php:241

Stack trace:
#0 /Users/buismaarten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(241): {closure}(8192, 'Method Reflecti...', '/Users/buismaar...', 241)
#1 /Users/buismaarten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(198): phpDocumentor\Reflection\DocBlock\StandardTagFactory->getArgumentsForParametersFromWiring(Array, Array)
#2 /Users/buismaarten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(122): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('ClientCapabilit...', 'param', Object(phpDo...
```

**Comment by buismaarten** [comment]
Just updated the issue with more details, hopefully PHP 8.0 support will be added soon.

**Comment by Kein** [comment]
I dont think it will, last activity was in q4 of 2019, I think the original author is now busy with other things.

**Comment by tracerrx** [comment]
My Macbook Pro also upgraded to PHP 8, Same issue.

**Comment by asolux** [comment]
But it would be a shame for this good extension.

**Comment by buismaarten** [comment]
Moved to https://github.com/felixfbecker/php-language-server/issues/798

**Comment by Flynsarmy** [comment]
Why was this moved and closed? This repo was last updated March 2020. The one it was moved to was last updated Dec 2018...

**Comment by DAVID24Ma** [comment]
> Why was this moved and closed? This repo was last updated March 2020. The one it was moved to was last updated Dec 2018...

As those two repo are from the same author, and the language server is the one that handle the php code, this extension is just the interface with vscode.

**Comment by hetao29** [comment]
https://github.com/felixfbecker/php-language-server/issues/798
