### ISSUE TITLE
problems in opened files setting

### ISSUE THREAD

**Issue by SailorMax** [felixfbecker/vscode-php-intellisense#53]
Steps to Reproduce:

1. install php-intellisense extension
2. open workspace with PHP files
3. open any PHP file

Expected: Problems panel has problems of only opened files

Actual: Problems panel has problems of total workspace.

Can you add setting to scan on problems only opened file(s)? I have too large workspace with many "prev-" temporary files. I don't need to see errors from temporary files. And I don't need to scan all files, because it take CPU resources.

thank you.

P.S. related with comment of https://github.com/Microsoft/vscode/issues/19018#issuecomment-274729014
file/line: https://github.com/felixfbecker/php-language-server/blob/d080c161a9e65e54ec28a4b9a3e3607f09232a9c/src/LanguageServer.php#L291

**Comment by felixfbecker** [comment]
I think https://github.com/felixfbecker/php-language-server/issues/164 or https://github.com/felixfbecker/php-language-server/issues/246 would solve your problem. You _do_ need to index all files because otherwise symbol search, type checking etc would not work.
