### ISSUE TITLE
php intellisense not found in vscode

### ISSUE THREAD

**Issue by FatlumGjinofci** [felixfbecker/vscode-php-intellisense#590]
When i try to install phpIntellisense in vscode extensions it didn't shows that.
It shows only phpIntelphense.

**Comment by jdrab** [comment]
If you look-up the extension page on marketplace:
https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense
You'll see there is a note 

This extension is now unpublished from Marketplace. You can choose to uninstall it.

**Comment by FatlumGjinofci** [comment]
@jdrab thanks

**Comment by aaronbauman** [comment]
I don't understand.
Is the extension no longer supported?
If it is still supported, how do I install it?

**Comment by AmineTech21** [comment]
I think there is another now it is a fork from the original PHP IntelliSense it's from Damjan Cvetko
