### ISSUE TITLE
Connection to server is erroring. Shutting down server.

### ISSUE THREAD

**Issue by DumboJetEngine** [felixfbecker/vscode-php-intellisense#6]
This is a question:

I am getting this error in the output window:

> Connection to server is erroring. Shutting down server.

What does this mean?
Do I have to install anything else apart form the VS Code extension? :^)
I don't even know what the language server is supposed to be (I guess the parser for the language?).
If you can help it would be cool. :)

Paradoxically, the "format code" option seems working (maybe it is native functionality of VS Code that you override?), but not the symbol listing.

**Comment by felixfbecker** [comment]
Do you have PHP 7 installed and in your PATH?

**Comment by DumboJetEngine** [comment]
Oh... I have PHP 5.3.8.
Does it depend on PHP 7?

Also, I don't have it in the PATH env. variable.
Can I instead have it in a workspace setting (I had some bad experiences with the PATH variable reaching max length in the past and it would be nice to avoid adding it there)?

**Comment by DumboJetEngine** [comment]
New info:

By adding the PHP 5.3.8 path in my user's PATH env. variable cause this error:

> The PHP Language Client server crashed 5 times in the last 3 minutes. The server will not be restarted.

I guess my PHP version is not supported. :(

**Comment by felixfbecker** [comment]
The language server (basically a process that runs in the background and provides completion etc) uses latest PHP features of PHP 7. You can still develop your app in whatever version you need, but the language server currently needs PHP 7 installed in your PATH.

**Comment by DumboJetEngine** [comment]
OK.
Thanks! :)

**Comment by DumboJetEngine** [comment]
I have a suggestion on this:

I think it would be very good if you provided a VSCode setting for the path of PHP 7.
The PATH environment variable tends to clutter with paths and reach its max length very often. :(
I would like to use a portable version of PHP 7, if that was possible, and only define the path from inside the VSCode. :)
I see other extensions to this:

>    "php.validate.executablePath": "C:\\Program Files\\php-7.0.11\\php.exe",

That's just a suggestion. :)

**Comment by felixfbecker** [comment]
See #11, should be easy to implement, PR welcome

**Comment by DumboJetEngine** [comment]
OK.
This is my first time trying to do anything serious with Node but I will give it a shot.
Any idea why I get this error when I run the build task? :

> Error: Cannot find module 'c:\Users\user\Desktop\php-intel\node_modules\vscode\bin\compile'

I guess, that without solving this I cannot do anything... :(

I did a :
> npm install vscode

...but the generated folder only contains `install` and `test`, no `compile`. :(

**Comment by DumboJetEngine** [comment]
I now see the main page of the project :

> composer install 
npm install
npm run compile
code .

Let me try with this one...

**Comment by DumboJetEngine** [comment]
OK.
I have followed the steps but I used a small variation because I have a tendency of not installing things but have them portable:

> php composer.phar install   <- Here I did it differently - hopefully it's the same...
npm install
npm run compile

It seems that it compiled the extension and it works, but I got this error :

```
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\node-v4.6.0\\node.exe" "C:\\Program Files\\node-v4.6.0\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error php-intellisense@0.0.9 compile: `node ./node_modules/vscode/bin/compile -p ./`
17 error Exit status 2
18 error Failed at the php-intellisense@0.0.9 compile script 'node ./node_modules/vscode/bin/compile -p ./'.
18 error This is most likely a problem with the php-intellisense package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./node_modules/vscode/bin/compile -p ./
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs php-intellisense
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls php-intellisense
18 error There is likely additional logging output above.
```

Donno if you have seen this before...

**Comment by felixfbecker** [comment]
Is there no other error output? It apparently did not compile the extension. Do you have an `out` dir created? Do you have node in your path? Also, try a newer Node / NPM version.

**Comment by DumboJetEngine** [comment]
These are the only lines that start with `error`, :(
But it does generate the `out` folder and the extension files and the test folder with its contents.
The extension seems to work as well when debugging.
So, not sure what this is... :^)
Anyway.
Maybe it's something small.
Maybe something I did previously is not be very correct.
But the extension seems to work so far when debugging, so I can probably try adding that setting (if I discover how). :)

**Comment by DumboJetEngine** [comment]
> if I discover how to access its value

Found it! :)

**Comment by DumboJetEngine** [comment]
OK.
I have created a Pull Request! :)
That was a very interesting experience for me!

First time writing NodeJS code, first time writing TypeScript, first time working on a VSCode extension (debugging is cool!), first time working with Composer, second time touching NPM and node.exe.

You may find the changes bigger than expected.
If you don't like them, I have no problem if you turn them down. ;)

**Comment by DumboJetEngine** [comment]
One possible improvement: The variables  `php7Found` and `errorList` might not be needed.

**Comment by DumboJetEngine** [comment]
I have tried to make the linter happy by fixing many issues, but it still nags for some reason.
Not sure what it wants anymore... :(
https://github.com/felixfbecker/vscode-php-intellisense/pull/18
Other than that the fix seem working and the code seems clean to me.
