### ISSUE TITLE
URL is not a valid Fqsen

### ISSUE THREAD

**Issue by unional** [felixfbecker/vscode-php-intellisense#64]
```php
/**
 * Some desc
 * @see http://google.com
 */
function foo() { ... }
```
 Complains: `"\http://google.com" is not a valid Fqsen.

**Comment by felixfbecker** [comment]
> **Note: This is just the VS Code extension that spawns the actual language server. The language server itself is implemented purely in PHP [in its own repository](https://github.com/felixfbecker/php-language-server), all features need to be implemented there and all issues should be reported there.**

https://github.com/felixfbecker/php-language-server/issues?utf8=%E2%9C%93&q=url%20not%20a%20valid%20fqsen%20

**Comment by unional** [comment]
Thanks @felixfbecker 🌷
