### ISSUE TITLE
Autocomplete not working?

### ISSUE THREAD

**Issue by snizemic** [felixfbecker/vscode-php-intellisense#67]
I don't know if I am doing something wrong or if it is even possible but I have framework classes in vendor folder so I would thought that autocomplete function hinting/completing these classes, eg. in use statement, function parameters etc. Every other function of your extension works well, great job! But autocomplete is not, even with your PDO example.

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#276
