### ISSUE TITLE
Throws errors in git diff view of vscode.

### ISSUE THREAD

**Issue by hworld** [felixfbecker/vscode-php-intellisense#68]
`Message: InvalidArgumentException: Not a valid file URI: inmemory://model/26 in...`

I think it may be because the diff views shown aren't on disk, but instead loaded in memory? To reproduce, just open a repository folder, modify a PHP file, switch into the Git panel, and select the modified file.

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#284
