### ISSUE TITLE
A way to ignore folders?

### ISSUE THREAD

**Issue by ryanbowden** [felixfbecker/vscode-php-intellisense#70]
I work on a big project which includes lots of files.  Which can have a lot of issue in them and make it really slow to run. 

How can I tell it folders not to search? Or if there is a way can it be added to the documentation.

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20exclude%20files%20
