### ISSUE TITLE
Aliases with class_alias not supported

### ISSUE THREAD

**Issue by bfranklyn** [felixfbecker/vscode-php-intellisense#71]
for example if i have a class defined as `class Extremely_Long_Class_Name` aliased as `Name`
i can call a static method 'foo' from the class using either the full class name or the aliased name like this.

Extremely_Long_Class_Name::foo()  // go to definition on foo works fine

Name::foo() // go to definition on foo doesn't work

**Comment by felixfbecker** [comment]
Please post a full code snippet to reproduce. This should be handled.

**Comment by dgadelha** [comment]
He means that when you use an alias for a class:

```
use Extremely_Long_Class_Name as Name;
```

The **Go to definition** feature doesn't work when you use the alias:

```
Name::foo();
```

But works with the full class name:

```
Extremely_Long_Class_Name::foo();
```

**Comment by bfranklyn** [comment]
Sorry for the late reply.

Go to definition works fine for aliases created with  `use class as` but not for aliases created with the `class_alias` function, see pic below.

![php_intellisense](https://cloud.githubusercontent.com/assets/6205670/23669081/0a0e1740-0331-11e7-9586-1f641ef63668.PNG)

**Comment by SplicePHP** [comment]
Just had the same issue.
For anyone else who needs a quick fix.
There is a rather simple workaround though not ideal.

Create a dummy directory somewhere in your project
Create the file **dummy/MyClass.php**
```
class MyClass extends Extremely_Long_Class_Name_MyClass {

}
```
You do not need to include it anywhere in your project, its existence alone should fix your intellisense.
