### ISSUE TITLE
intellisense should suggest files to be included

### ISSUE THREAD

**Issue by arimourao** [felixfbecker/vscode-php-intellisense#76]
One thing that I still miss from Netbeans is it's superb intellisense that offers suggestions to include files from a given path as you are typing plus bringing the docs (if available).

**From Netbeans:**

![screenshot from 2017-02-17 16 59 16](https://cloud.githubusercontent.com/assets/7979806/23079507/5222b622-f534-11e6-8df9-e5b5a3632a27.png)

![screenshot from 2017-02-17 16 59 39](https://cloud.githubusercontent.com/assets/7979806/23079522/60633c8e-f534-11e6-9cbb-d8513abdc825.png)

**vscode-php-intellisense**

![screenshot from 2017-02-17 17 00 12](https://cloud.githubusercontent.com/assets/7979806/23079479/3652bad2-f534-11e6-95ed-85e1c940b2ac.png)

How can we implement similar functionality?

**Comment by felixfbecker** [comment]
I think you mean IntelliSense for namespaces, please open this at the language server repo if it is not already tracked.
