### ISSUE TITLE
issue with <?php in shortCode or outside of php tag

### ISSUE THREAD

**Issue by larrypaul93** [felixfbecker/vscode-php-intellisense#78]
Extension work well in <?php ?> area. but not work in shorten tag.
it have problem out side of php tag
![image](https://cloud.githubusercontent.com/assets/10649897/23138205/c18b4e30-f7c7-11e6-9b21-aaf660a77229.png)
![image](https://cloud.githubusercontent.com/assets/10649897/23138216/cef8700c-f7c7-11e6-8f9a-5666eb21bc29.png)

**Comment by felixfbecker** [comment]
Do you have `short_open_tags` enabled in php.ini?

**Comment by larrypaul93** [comment]
seems working after enabling short tags. but still have issue outside tag. is it possible to disable php tag suggestion through setting.

**Comment by felixfbecker** [comment]
What issue outside of tag?

**Comment by larrypaul93** [comment]
![image](https://cloud.githubusercontent.com/assets/10649897/23141261/c773993c-f7d7-11e6-8339-827eb0184b0c.png)

**Comment by hinklor** [comment]
I have the same issue. Anything I type outside of php tags results in <?php being suggested

![image](https://cloud.githubusercontent.com/assets/26404009/23893125/9ba0ea86-089d-11e7-912e-ba4a2404c589.png)

**Comment by ishegg** [comment]
Was this ever fixed? Still having this behavior in version 1.5.2, VSCode 1.17.2.
