### ISSUE TITLE
Not working, no indicators/console messages

### ISSUE THREAD

**Issue by QwertyZW** [felixfbecker/vscode-php-intellisense#79]
Version: 1.1.2
VSCode: 1.9.1

I've got this installed and opened up a wordpress php directory as my workspace and tried clicking/hovering/typing to reference variables but none of the features worked.

The directory is a remote linux directory mounted as a drive on windows 10 (So the  requires/includes use '/'s)

I don't see any indication of the extension indexing the workspace (as opposed to this one here https://marketplace.visualstudio.com/items?itemName=HvyIndustries.crane) or doing anything interesting for that matter.

In the debug console I see this 
```
[Extension Host] PHP process connected               extensionHost.ts:282 
```

I have php7.1 in my path and I can access it from an admin powershell, a user powershell and cygwin

**Comment by felixfbecker** [comment]
Without any console messages I'm afraid it is impossible for me to help you. Did you check the output panel?

**Comment by QwertyZW** [comment]
Yea there's nothing there. Trying a different approach to mirror remote directory.
