### ISSUE TITLE
Fails to validate php version

### ISSUE THREAD

**Issue by jusesilva** [felixfbecker/vscode-php-intellisense#8]
I'm running Gentoo and this extension fails to compare the version of php:
```
The language server needs at least PHP 7 installed and in your PATH. Version found: 7.0.10--pl0-gentoo
```

**Comment by felixfbecker** [comment]
that is a very weird version string. Is it only Gentoo that does this kind of thing? Do you know if this is a pattern (like the double dash)?

**Comment by jusesilva** [comment]
I don't know.. I fixed the version with: ```if (!semver.satisfies(version.split('-')[0]], '>=7.0')) {```
but it is only a temporal work around .. for semver anything with "-" is "less than" the specified version:
```bash
$ semver -r '>=7.0' '7.0.10'
7.0.10
$ semver -r '>=7.0' '7.0.10-rc1'
$ semver -r '>=7.0' '7.0.10--pl0-gentoo'
$ semver -r '>=7.0' '7.0.10-pl0-gentoo'
$ semver -r '>=7.0' '7.0.10-gentoo'
$ semver -r '^7.0' '7.0.10-rc1'
$ semver -r '^7.0' '7.0.10'
7.0.10
$
```

**Comment by felixfbecker** [comment]
Yes, that's because in semver a `-` means a pre release, and a pre-release is "before" the stable version of the same number. You fix will not work to validate _actual_ prereleases like `7.0.0-beta1`. Which is why I asked if this double dash is a pattern that can be relied upon.

**Comment by MadHed** [comment]
I just want to chime in to say that I have the same problem on elementary OS. The extension fails to load with:

> TypeError: Invalid Version: 7.0.8--0ubuntu0.16.04.2

**Comment by felixfbecker** [comment]
Seems like we can split by the `--`

**Comment by MadHed** [comment]
If you want to test, the actual output from _php --version_ is:

> PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.8-0ubuntu0.16.04.2, Copyright (c) 1999-2016, by Zend Technologies

Note: There's only one dash, I guess the seconds dash gets added by your format normalization logic.

**Comment by felixfbecker** [comment]
Thanks for that info! Very important

**Comment by felixfbecker** [comment]
Could you try this release?
[php-intellisense-0.0.5.vsix.zip](https://github.com/felixfbecker/vscode-php-intellisense/files/474130/php-intellisense-0.0.5.vsix.zip)

**Comment by MadHed** [comment]
> Could not open input file: /home/xxx/.vscode/extensions/felixfbecker.php-intellisense-0.0.5/vendor/felixfbecker/language-server/bin/php-language-server.php

**Comment by MadHed** [comment]
I merged your changes to extension.js into the marketplace release and was able to start the extension.

**Comment by felixfbecker** [comment]
I'm confused. Can I release this or not?

**Comment by felixfbecker** [comment]
Ah sorry, it seems like I had a symlink in place to a development version of the language server.

**Comment by felixfbecker** [comment]
v0.0.6
