### ISSUE TITLE
Find "use Namespace"

### ISSUE THREAD

**Issue by sugarmaster** [felixfbecker/vscode-php-intellisense#80]
I've been using sublime for a long time and someone told me to switch to vscode.

I found it perfect for coding and very sublime-like but it lacks one thing: find use.

I'm talking about pressing a shortcut/context-menu button and it automatically adds the required class to the top of the file like so:

Products::find(1);
|
v
use App\Models\Products;

**Comment by jens1o** [comment]
see https://github.com/felixfbecker/php-language-server/issues/234

**Comment by felixfbecker** [comment]
Thanks @jens1o
