### ISSUE TITLE
Fuzzy symbol matching

### ISSUE THREAD

**Issue by johnbillion** [felixfbecker/vscode-php-intellisense#82]
When searching for a symbol using `Go to Symbol in File...` or  `Go to Symbol in Workspace...` it would be great to allow fuzzy symbol name matching. Good fuzzy matching is one of the great features of Sublime Text that I miss in VS Code.

I'm not sure if this is the responsibility of VS Code or the responsibility of language-specific intellisense providers such as PHP IntelliSense.

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#318
