### ISSUE TITLE
'is not a valid Fqsen' odd behaviour

### ISSUE THREAD

**Issue by QwertyZW** [felixfbecker/vscode-php-intellisense#84]
Php: 7.1.2
VSCode: 1.10.1
Adapter: 1.1.3

The extension is underlining a lot more than it needs to I believe. This is from the wordpress code base.

![notavalidfqsen](https://cloud.githubusercontent.com/assets/8478946/23641290/980d2a52-02c0-11e7-8b31-da18036d7513.PNG)

Mousing over any part of the underlining shows the tooltip displayed.

**Comment by jens1o** [comment]
Well, it is not valid fqsen, that's why it is underlined. See https://github.com/felixfbecker/php-language-server/issues/244

**Comment by QwertyZW** [comment]
Thanks, for the references.
