### ISSUE TITLE
Option to ignore directories for error reporting

### ISSUE THREAD

**Issue by Tilogorn** [felixfbecker/vscode-php-intellisense#85]
It would be nice if one could ignore certain directories for error reporting, e.g. with a setting like
`"php_intellisense.ignoreDirections" : ['system', 'application/libraries']`.

My use case: CodeIgniter in the root directory
```
myproject/
├── application/
│   ├── // My custom files
│   ├── libraries
├── system/
│   ├── // CodeIgniter source files
```

Through Intellisense I get a bunch of errors for CodeIgniter-specific problems in the error console like
```
Email.php (system/libraries/)
[php] "\https://github.com/bcit-ci/CodeIgniter/issues/4963" is not a valid Fqsen.
```

But I don't want to care nor edit external dependencies. But I want to satisfy my error output.

**Comment by felixfbecker** [comment]
Duplicate https://github.com/felixfbecker/php-language-server/issues/164
