### ISSUE TITLE
can't go to define in CodeIgniter project

### ISSUE THREAD

**Issue by boer0924** [felixfbecker/vscode-php-intellisense#87]
In my ci project, the code like `$this->user_model->verifyPassword()`, the verifyPassword() function is my Model method, can't go to function define where. Can help me ?

**Comment by jens1o** [comment]
Did you wrote a doc comment on the `user_model` var? Please show us the code.

**Comment by boer0924** [comment]
@jens1o  the user_model is an autoload class. or use CI load method, like 
```
$this->load->model('user_model');
$verify = $this->user_model->verifyPassword($password, $row->password);
```

This guide maybe you want: https://www.codeigniter.com/user_guide/general/models.html#loading-a-model

My English isn't very good, please don't mind.

**Comment by boer0924** [comment]
@

**Comment by jens1o** [comment]
Try to document it with the class description(in the model class):

```php
/**
 * Represents a class.
 * 
 * @author      jens1o
 * @copyright	2001-2017 Jens Hausdorf
 * @license	MIT License
 *
 * @property-read	UserProfileModel $userProfileModel Represents a user profile
 */
class UserModel extends AbstractModel {
     // and so on
}
```

Now try: `$this->userProfileModel` and check wether it works.

**Comment by boer0924** [comment]
Not work. when I hover `verifyPassword` method show loading.

Other code can be perfect go to define, only just like 
```
$this->someclass->somemethod();
```
not work.

**Comment by jens1o** [comment]
Please show us the class you'd modified.

**Comment by felixfbecker** [comment]
The root of this could be multiple issues.

- You may not have a documented the definitions correctly
- `$this` may not be resolved correctly
- `@property-read` is not used afaik

I would ask you to look into this more and when you know more specifics, please open an issue _at the language server repository_ (see readme) with code snippets to reproduce. Chances are, there is already one open.

**Comment by isabelfr** [comment]
I had the same problem. 
PHP intellisense for codeigniter extension fixed it.
