### ISSUE TITLE
Follow References for traits

### ISSUE THREAD

**Issue by GeraldNDA** [felixfbecker/vscode-php-intellisense#89]
It'd be great if I could go to the trait definitions or see the definition of methods defined by traits. Also parent seeing the definition for method calls and $this method calls would also be amazing. 

Examples:
![image](https://cloud.githubusercontent.com/assets/11413630/23914201/a0c8e36a-08bb-11e7-8e65-c735496a88b2.png)

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#331
