### ISSUE TITLE
How to make the VSCode extension work

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/vscode-php-intellisense#9]
_From @BernalCarlos on September 13, 2016 13:53_

Hi,

I just downloaded the extension for VSCode, but it does not seem to work. For example, i cant find symbols (it says "unfortunately we have no symbol information for the file") or format code (the option doesn't appear on the context menu).

I'm using Linux Mint 18, the latest version of VSCode, and installed PHP 7 using `sudo apt-get install php`.

Is there something else i'm supposed to do?

Thank you.

_Copied from original issue: felixfbecker/php-language-server#26_

**Comment by felixfbecker** [comment]
Hm, very hard to help you there... All I can say is it works on my machine 😐

Could you try to run it from source and see what gets logged in the debug console?

**Comment by BernalCarlos** [comment]
Sure, I could try that. I just don't know how. I'm new to VSCode.

**Comment by felixfbecker** [comment]
Some guidance is here https://github.com/felixfbecker/vscode-php-intellisense#contributing
You need composer and NodeJS/npm installed.

**Comment by Alenore** [comment]
Just in case it could help someone, I experienced the same problem. It was caused by a warning on php execution, linked to a missing .so/.dll.

**Comment by felocru** [comment]
Hello, I do not know if this is appropriate to comment.
But I do not get to run the autocompletion.
All other features work well for me.

**Comment by felixfbecker** [comment]
@felocru No, if you experience an issue, please open a new issue. But this extension is WIP, it does not provide autocompletion yet, only the features in the readme.
