### ISSUE TITLE
Suggestion - make autocompletion case insensitive

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [felixfbecker/vscode-php-intellisense#90]
This is a bit akward for me because I'm used to this.

as an example:

```
<?php

$aVar = [];
$nFoo = 1;
```

If I want the editor to autocomplete `$aVar` and I wrote `$a`, `$aVar` appears on list to autocomplete, but if I write `$av`, the variable disapears from the list.

 -----

Another thing I noticed is that when I disable `php.suggest.basic`, the PHP core autocompletions stops working, I don't know if this is part of the normal behavior, but It would be excellent to have  your own code + PHP core functions autocompletion.

Thanks for your work with this plugin, it's great!

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/php-language-server#332

**Comment by felixfbecker** [comment]
> Another thing I noticed is that when I disable php.suggest.basic, the PHP core autocompletions stops working, I don't know if this is part of the normal behavior, but It would be excellent to have your own code + PHP core functions autocompletion.

This should work, please open a separate issue with reproduction steps.
