### ISSUE TITLE
Change all ocurrences - not respecting scope

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [felixfbecker/vscode-php-intellisense#91]
If you have two methods and both have a variable with the same name and you choose `change all occurrences` it changes literally all occurrences regarding where is this variable being used and it's scope.

**Comment by jens1o** [comment]
That's true, because it doesn't rename the symbol, since it's not supported by this extension, yet. So you're using the default vscode function.

**Comment by DasJott** [comment]
Tha tis normal behaviour of vscode. It does what it says: Change all occurences.
