### ISSUE TITLE
PHP core functions autocompletion is not working

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [felixfbecker/vscode-php-intellisense#92]
When I disable `php.suggest.basic` the PHP core autocompletions stops working.

 I don't know if this is part of the normal behavior, but It would be excellent to have your own code + PHP core functions autocompletion.

This is a test. I'm trying to get `array_map` function from the PHP core:

![test](https://cloud.githubusercontent.com/assets/5341310/23973339/4cf08438-099b-11e7-9369-ff5a45617768.gif)

My VS Code version is 1.10.2 (1.10.2)  on OS X

And I took an screenshot to my user settings:

![screen shot 2017-03-15 at 4 23 16 pm](https://cloud.githubusercontent.com/assets/5341310/23973436/d23f6244-099b-11e7-992a-671892b7f30d.png)

**Comment by zRnatoNeto** [comment]
I have this same problem :(

**Comment by jens1o** [comment]
That's true. Only when you're hovering about some php core function, it will be explained. I think Felix is working on this.

**Comment by DasJott** [comment]
This extension does not work for me at all. It doesn't do a single thing as described. In fact it makes no difference at all whether installed or not.
That's a pity, because I would love to be able to use vscode for php as well...

**Comment by felixfbecker** [comment]
@DasJott any errors in the console? Does it work in the test fixtures?

**Comment by DasJott** [comment]
@felixfbecker sadly no errors in the dev console - already checked that. Is there anything I can do to help figuring things out?

**Comment by DasJott** [comment]
Strange thing is: In some classes I can jump to definition (Ctrl click on symbol) and in some I can't. In a very clean environment like an empty php file it works good.
I am working on a rather huge project, maybe that is a point?
It looks like there are factors disturbing the extension.

**Comment by felixfbecker** [comment]
Can you give an [SSCCE](http://www.sscce.org/)?

**Comment by DasJott** [comment]
As soon as I find out what works and what not, I will!
Sadly this project is no open source and I would propably lose my job if I's give away source from it ;)

**Comment by felixfbecker** [comment]
Closing as inactive
