### ISSUE TITLE
Manually trigger indexing for a directory - Feature request

### ISSUE THREAD

**Issue by QwertyZW** [felixfbecker/vscode-php-intellisense#94]
Adapter: 1.1.3
Vscode: 1.10.2

Often times I run into situations where It feels like the adapter just won't index certain directories.  Sometimes it randomly decides it's about time it picked up  a directory and started indexing it.

I have 2 functions that are called side by side, the adapter seemed to have indexed only the directory that contained one of them. When hovering over the indexed one it shows a tooltip with the function definition. Hovering over the other one shows a tooltip that says 'Loading..."

Reloading the windows does not help.

I'd like to have the ability manually trigger indexing for a particular directory, at least as a means of alleviating the problem at hand.

Thanks

**Comment by felixfbecker** [comment]
Indexing is always triggered by reloading the window, for all directories. If you have a specific reproduction case, please open at the language server repo, not here.

**Comment by QwertyZW** [comment]
That's good to know, thanks!
