### ISSUE TITLE
Info: spawn EACCES

### ISSUE THREAD

**Issue by MaxOrelus** [felixfbecker/vscode-php-intellisense#95]
I'm getting this notification at the top of my screen when installing this extension. I've already set both my settings as shown below:

```
"php.suggest.basic":false,
"php.validate.executablePath": "/usr/local/opt/php70"
```

The `php.executablePath` setting doesn't exist (at least that's what VS code settings linter indicates), so I have only the two settings I mentioned above. 

How do I get rid of the notification?

**Comment by MaxOrelus** [comment]
Image Proof:

![Code Error](http://i.imgur.com/skC4L74.png)

![Code Settings](http://i.imgur.com/djajJKj.png)

**Comment by felixfbecker** [comment]
PHP IntelliSense just shows you the error it got from the OS - no access permissions on the binary.

**Comment by MaxOrelus** [comment]
Okay, so how do you go about fixing it? Do you `chmod` the binary to a certain permission level? Do you change ownership?

**Comment by vitorhsb** [comment]
I'm running into the same issue. What do you suggest to resolve this issue?

**Comment by felixfbecker** [comment]
What are the permissions of the binary?

**Comment by vitorhsb** [comment]
So it appears I did managed to get it working.
I'm running on MacOSX, and installed php70 using brew. UNIX permissions are -rwxr-xr-x (0755).
The following configuration is mandatory.

```
"php.suggest.basic": false,
"php.executablePath": "/usr/local/opt/php70/bin/php"
```

The php.executablePath is listed as an unknown configuration setting which had mislead me. This configuration should be listed as a contribution by this extension.

**Comment by mathmul** [comment]
Trying to set `"php.suggest.basic": false` in user and/or workspace settings, but VSCode dims it out with a note: "Unknown Configuration Setting". Found these settings instead. Probably should make them all false (default is true).

```php
"[php]": {
    "editor.suggest.showClasses": false,
    "editor.suggest.showColors": false,
    "editor.suggest.showConstants": false,
    "editor.suggest.showConstructors": false,
    "editor.suggest.showCustomcolors": false,
    "editor.suggest.showDeprecated": false,
    "editor.suggest.showEnumMembers": false,
    "editor.suggest.showEnums": false,
    "editor.suggest.showEvents": false,
    "editor.suggest.showFields": false,
    "editor.suggest.showFiles": false,
    "editor.suggest.showFolders": false,
    "editor.suggest.showFunctions": false,
    "editor.suggest.showIcons": false,
    "editor.suggest.showInlineDetails": false,
    "editor.suggest.showInterfaces": false,
    "editor.suggest.showIssues": false,
    "editor.suggest.showKeywords": false,
    "editor.suggest.showMethods": false,
    "editor.suggest.showModules": false,
    "editor.suggest.showOperators": false,
    "editor.suggest.showProperties": false,
    "editor.suggest.showReferences": false,
    "editor.suggest.showSnippets": false,
    "editor.suggest.showStatusBar": false,
    "editor.suggest.showStructs": false,
    "editor.suggest.showTypeParameters": false,
    "editor.suggest.showUnits": false,
    "editor.suggest.showUsers": false,
    "editor.suggest.showValues": false,
    "editor.suggest.showVariables": false,
    "editor.suggest.showWords": false,
},
```
