### ISSUE TITLE
Mixed PHP code with HTML formatting problem...

### ISSUE THREAD

**Issue by mjoksa** [felixfbecker/vscode-php-intellisense#96]
I just got involved in some old PHP project where all files are mix of PHP code and HTML markup and I found out that format code does nothing. 

I tried to find other post that address this issue, could not find any, so I was wondering if this beautiful extension of yours should format file that is mix of HTML and PHP code?

Cheers

**UPDATE:** Can anyone answer please? If I cannot use this plugin to format mixed PHP&HTML code, I will have to try to find another solution

**Comment by shaneparsons** [comment]
I'm noticing the same on my end... In my case it's with laravel blade files though.

**Comment by felixfbecker** [comment]
Formating is done by PHP CodeSniffer atm, in the future it will be handled by the parser correctly. If you have a specific bug with a reproduction case please open an issue at the language server repository, not here.
