### ISSUE TITLE
Suggestion: Hand-over to HTML intellisense when outside php tags

### ISSUE THREAD

**Issue by twinklebob** [felixfbecker/vscode-php-intellisense#98]
As per Microsoft/vscode#670, there's no HTML autocomplete within PHP files.

I have absolutely no idea how this works, but is it possible to hand off to the HTML autocomplete when you are outside php tags `<? ?>`?

**Comment by felixfbecker** [comment]
I outlined the requirements to make this work partly in that thread and in discussion with @mousetraps

**Comment by twinklebob** [comment]
My apologies, for some reason as I read through that issue it didn't click that you were you, if that makes sense. Seems like a complicated thing to achieve with the way they've set it up in VSCode.
